"""Materialize runtime path state and typed core configuration containers.

This module bridges resolved configuration and workspace layout into a frozen
:class:`WorkspaceContext` stored in a :class:`~contextvars.ContextVar`,
consumed by sync, CLI, and MCP surfaces.

Usage:
    Call :func:`init_paths` after configuration and workspace resolution to
    build and activate the :class:`WorkspaceContext` for the current execution
    context. Access the active context via :func:`get_context`.
"""

from __future__ import annotations

import logging
from contextvars import ContextVar
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .enums import DirName, FileName, ProviderCapability, Resource, Tool

logger = logging.getLogger(__name__)

# AUTO-GENERATED header constant
CONFIG_HEADER = "<!-- AUTO-GENERATED by cli.py config sync. -->"


@dataclass
class ToolConfig:
    """Configuration for a single AI tool destination (e.g. claude, gemini).

    Attributes:
        name: Short identifier for the tool (e.g. ``"claude"``).
        rules_dir: Directory where synced rule files are written, or ``None``
            if the tool does not use rules files.
        skills_dir: Directory where synced skill files are written, or ``None``
            if the tool does not use skill files.
        agents_dir: Directory where synced agent files are written, or ``None``
            if the tool does not use agent files.
        config_file: Path to the tool's main config file (e.g. ``CLAUDE.md``),
            or ``None`` if not applicable.
        native_config_file: Path to a tool-native configuration file that is
            not markdown-based (for example ``.codex/config.toml``), or
            ``None`` if not applicable.
        rule_ref_dir: Directory whose markdown files should be referenced from
            ``config_file``. Defaults to ``rules_dir`` when omitted.
        rule_ref_config_file: Optional secondary config file that carries
            ``@rules/...`` references, separate from ``config_file``.
            Currently unused; retained for future providers that need a
            secondary config file distinct from their root config.
        system_file: Path to the tool's system prompt file, or ``None`` if the
            tool does not have a dedicated system file.
        emit_system_rule: Whether shared system content should be materialized
            as a rule file when ``system_file`` is absent.
        capabilities: Declared provider capabilities.  Used by install, sync,
            and dry-run to reason about what each provider supports.
    """

    name: str
    rules_dir: Path | None
    skills_dir: Path | None
    agents_dir: Path | None = None
    config_file: Path | None = None
    native_config_file: Path | None = None
    rule_ref_dir: Path | None = None
    rule_ref_config_file: Path | None = None
    system_file: Path | None = None
    emit_system_rule: bool = True
    capabilities: frozenset[ProviderCapability] = frozenset()


@dataclass
class SyncResult:
    """Accumulator for file synchronization statistics.

    Attributes:
        added: Number of files newly created at the destination.
        updated: Number of existing files that were overwritten.
        skipped: Number of files that were intentionally not written
            (e.g. transform returned ``None``, or safety guard triggered).
        pruned: Number of stale destination files that were deleted.
        errors: List of error message strings for files that failed to sync.
        items: Per-file action log  - list of ``(path, action)`` tuples for
            dry-run rendering.
        warnings: Advisories about what ``--force`` would change beyond the
            default sync.
    """

    added: int = 0
    updated: int = 0
    skipped: int = 0
    pruned: int = 0
    errors: list[str] = field(default_factory=list)
    items: list[tuple[str, str]] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class WorkspaceContext:
    """Immutable snapshot of resolved workspace paths and tool configuration.

    Attributes:
        root_dir: Workspace root path.
        target_dir: Target directory (alias for root in standard layouts).
        rules_src_dir: Source directory for rule files.
        skills_src_dir: Source directory for skill files.
        agents_src_dir: Source directory for agent files.
        system_src_dir: Source directory for system prompt files.
        templates_dir: Source directory for template files.
        hooks_dir: Source directory for hook files.
        tool_configs: Per-tool configuration mapping.
    """

    root_dir: Path
    target_dir: Path
    rules_src_dir: Path
    skills_src_dir: Path
    agents_src_dir: Path
    system_src_dir: Path
    templates_dir: Path
    hooks_dir: Path
    tool_configs: dict[Tool, ToolConfig] = field(default_factory=dict)


_workspace_ctx: ContextVar[WorkspaceContext] = ContextVar("_workspace_ctx")


def get_context() -> WorkspaceContext:
    """Return the active :class:`WorkspaceContext`.

    Raises:
        LookupError: If :func:`init_paths` has not been called in this
            execution context.
    """
    return _workspace_ctx.get()


def set_context(ctx: WorkspaceContext) -> None:
    """Explicitly set the active :class:`WorkspaceContext`."""
    _workspace_ctx.set(ctx)


def _create_tool_cfg(
    tool: Tool,
    root: Path,
    tool_dir: str | None = None,
    rules: bool = True,
    skills: bool = True,
    agents: bool = True,
    config: FileName | None = None,
    system: FileName | str | None = None,
) -> ToolConfig:
    """Helper to create a ToolConfig with standard directory patterns."""
    t_dir = root / tool_dir if tool_dir else None
    rules_dir = t_dir / Resource.RULES.value if t_dir and rules else None
    return ToolConfig(
        name=tool.value,
        rules_dir=rules_dir,
        skills_dir=t_dir / Resource.SKILLS.value if t_dir and skills else None,
        agents_dir=t_dir / Resource.AGENTS.value if t_dir and agents else None,
        config_file=(t_dir / config.value) if t_dir and config else None,
        rule_ref_dir=rules_dir,
        system_file=(
            (t_dir / (system.value if isinstance(system, FileName) else system))
            if t_dir and system
            else None
        ),
    )


def init_paths(layout: Any) -> WorkspaceContext:
    """Build a :class:`WorkspaceContext` from a workspace layout or root Path.

    The context is stored in the module-level :class:`~contextvars.ContextVar`
    and also returned for convenience.

    Args:
        layout: A ``WorkspaceLayout`` instance providing the resolved target,
            vault, and framework directories, OR a ``pathlib.Path`` to the
            project root (which will be resolved into a layout).
    """
    from ..config import get_config, resolve_workspace

    if isinstance(layout, Path):
        # Backward compatibility for tests passing a Path root
        layout = resolve_workspace(target_override=layout)

    cfg = get_config()

    target = layout.target_dir
    vaultspec = layout.vaultspec_dir

    rules_src_dir = vaultspec / Resource.RULES.value / Resource.RULES.value
    skills_src_dir = vaultspec / Resource.RULES.value / Resource.SKILLS.value
    agents_src_dir = vaultspec / Resource.RULES.value / Resource.AGENTS.value
    system_src_dir = vaultspec / Resource.RULES.value / Resource.SYSTEM.value
    templates_dir = vaultspec / Resource.RULES.value / Resource.TEMPLATES.value
    hooks_dir = vaultspec / Resource.RULES.value / Resource.HOOKS.value
    shared_agents_root = target / DirName.ANTIGRAVITY.value

    gemini_dir = target / cfg.gemini_dir

    # Build Tool Configurations
    _pc = ProviderCapability
    tool_configs: dict[Tool, ToolConfig] = {
        Tool.CLAUDE: ToolConfig(
            name=Tool.CLAUDE.value,
            rules_dir=target / cfg.claude_dir / Resource.RULES.value,
            skills_dir=target / cfg.claude_dir / Resource.SKILLS.value,
            agents_dir=target / cfg.claude_dir / Resource.AGENTS.value,
            config_file=target / FileName.CLAUDE.value,
            rule_ref_dir=target / cfg.claude_dir / Resource.RULES.value,
            capabilities=frozenset(
                {
                    _pc.RULES,
                    _pc.SKILLS,
                    _pc.AGENTS,
                    _pc.ROOT_CONFIG,
                    _pc.HOOKS,
                    _pc.TEAMS,
                    _pc.SCHEDULED_TASKS,
                }
            ),
        ),
        Tool.GEMINI: ToolConfig(
            name=Tool.GEMINI.value,
            rules_dir=gemini_dir / Resource.RULES.value,
            skills_dir=shared_agents_root / Resource.SKILLS.value,
            agents_dir=gemini_dir / Resource.AGENTS.value,
            config_file=target / FileName.GEMINI.value,
            rule_ref_dir=gemini_dir / Resource.RULES.value,
            system_file=gemini_dir / FileName.SYSTEM.value,
            capabilities=frozenset(
                {
                    _pc.RULES,
                    _pc.SKILLS,
                    _pc.AGENTS,
                    _pc.ROOT_CONFIG,
                    _pc.SYSTEM,
                    _pc.HOOKS,
                }
            ),
        ),
        Tool.ANTIGRAVITY: ToolConfig(
            name=Tool.ANTIGRAVITY.value,
            rules_dir=shared_agents_root / Resource.RULES.value,
            skills_dir=shared_agents_root / Resource.SKILLS.value,
            agents_dir=None,
            config_file=target / FileName.GEMINI.value,
            rule_ref_dir=shared_agents_root / Resource.RULES.value,
            system_file=None,
            emit_system_rule=False,
            capabilities=frozenset(
                {
                    _pc.RULES,
                    _pc.SKILLS,
                    _pc.ROOT_CONFIG,
                    _pc.WORKFLOWS,
                }
            ),
        ),
        Tool.CODEX: ToolConfig(
            name=Tool.CODEX.value,
            rules_dir=None,
            skills_dir=shared_agents_root / Resource.SKILLS.value,
            agents_dir=None,
            config_file=target / FileName.AGENTS.value,
            native_config_file=(
                target / DirName.CODEX.value / FileName.CONFIG_TOML.value
            ),
            rule_ref_dir=None,
            system_file=None,
            emit_system_rule=False,
            capabilities=frozenset(
                {
                    _pc.RULES,
                    _pc.SKILLS,
                    _pc.AGENTS,
                    _pc.ROOT_CONFIG,
                }
            ),
        ),
    }

    ctx = WorkspaceContext(
        root_dir=target,
        target_dir=target,
        rules_src_dir=rules_src_dir,
        skills_src_dir=skills_src_dir,
        agents_src_dir=agents_src_dir,
        system_src_dir=system_src_dir,
        templates_dir=templates_dir,
        hooks_dir=hooks_dir,
        tool_configs=tool_configs,
    )
    _workspace_ctx.set(ctx)
    return ctx
