"""Materialize runtime path state and typed core configuration containers.

This module bridges resolved configuration and workspace layout into the global
path constants and `ToolConfig` mappings consumed by sync, CLI, and MCP
surfaces.

Usage:
    Call `init_paths(...)` after configuration and workspace resolution to
    initialize the process-wide path layout used by downstream modules.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .enums import DirName, FileName, Resource, Tool

logger = logging.getLogger(__name__)

# AUTO-GENERATED header constant
CONFIG_HEADER = "<!-- AUTO-GENERATED by cli.py config sync. -->"


@dataclass
class ToolConfig:
    """Configuration for a single AI tool destination (e.g. claude, gemini).

    Attributes:
        name: Short identifier for the tool (e.g. ``"claude"``).
        rules_dir: Directory where synced rule files are written, or ``None``
            if the tool does not use rules files.
        skills_dir: Directory where synced skill files are written, or ``None``
            if the tool does not use skill files.
        agents_dir: Directory where synced agent files are written, or ``None``
            if the tool does not use agent files.
        config_file: Path to the tool's main config file (e.g. ``CLAUDE.md``),
            or ``None`` if not applicable.
        native_config_file: Path to a tool-native configuration file that is
            not markdown-based (for example ``.codex/config.toml``), or
            ``None`` if not applicable.
        rule_ref_dir: Directory whose markdown files should be referenced from
            ``config_file``. Defaults to ``rules_dir`` when omitted.
        system_file: Path to the tool's system prompt file, or ``None`` if the
            tool does not have a dedicated system file.
        emit_system_rule: Whether shared system content should be materialized
            as a rule file when ``system_file`` is absent.
    """

    name: str
    rules_dir: Path | None
    skills_dir: Path | None
    agents_dir: Path | None = None
    config_file: Path | None = None
    native_config_file: Path | None = None
    rule_ref_dir: Path | None = None
    system_file: Path | None = None
    emit_system_rule: bool = True


@dataclass
class SyncResult:
    """Accumulator for file synchronization statistics.

    Attributes:
        added: Number of files newly created at the destination.
        updated: Number of existing files that were overwritten.
        skipped: Number of files that were intentionally not written
            (e.g. transform returned ``None``, or safety guard triggered).
        pruned: Number of stale destination files that were deleted.
        errors: List of error message strings for files that failed to sync.
    """

    added: int = 0
    updated: int = 0
    skipped: int = 0
    pruned: int = 0
    errors: list[str] = field(default_factory=list)


# Module-level globals initialised by init_paths()
ROOT_DIR: Path = Path()
TARGET_DIR: Path = Path()  # Alias for ROOT_DIR
RULES_SRC_DIR: Path = Path()
SKILLS_SRC_DIR: Path = Path()
AGENTS_SRC_DIR: Path = Path()
SYSTEM_SRC_DIR: Path = Path()
TEMPLATES_DIR: Path = Path()
FRAMEWORK_CONFIG_SRC: Path = Path()
PROJECT_CONFIG_SRC: Path = Path()
HOOKS_DIR: Path = Path()
TOOL_CONFIGS: dict[Tool, ToolConfig] = {}


def _create_tool_cfg(
    tool: Tool,
    root: Path,
    tool_dir: str | None = None,
    rules: bool = True,
    skills: bool = True,
    agents: bool = True,
    config: FileName | None = None,
    system: FileName | str | None = None,
) -> ToolConfig:
    """Helper to create a ToolConfig with standard directory patterns."""
    t_dir = root / tool_dir if tool_dir else None
    rules_dir = t_dir / Resource.RULES.value if t_dir and rules else None
    return ToolConfig(
        name=tool.value,
        rules_dir=rules_dir,
        skills_dir=t_dir / Resource.SKILLS.value if t_dir and skills else None,
        agents_dir=t_dir / Resource.AGENTS.value if t_dir and agents else None,
        config_file=(t_dir / config.value) if t_dir and config else None,
        rule_ref_dir=rules_dir,
        system_file=(
            (t_dir / (system.value if isinstance(system, FileName) else system))
            if t_dir and system
            else None
        ),
    )


def init_paths(layout: Any) -> None:
    """(Re-)initialise all path globals from a workspace layout or root Path.

    Args:
        layout: A ``WorkspaceLayout`` instance providing the resolved target,
            vault, and framework directories, OR a ``pathlib.Path`` to the
            project root (which will be resolved into a layout).
    """
    global ROOT_DIR, TARGET_DIR, RULES_SRC_DIR
    global SKILLS_SRC_DIR, AGENTS_SRC_DIR, SYSTEM_SRC_DIR, TEMPLATES_DIR
    global FRAMEWORK_CONFIG_SRC, PROJECT_CONFIG_SRC
    global HOOKS_DIR, TOOL_CONFIGS

    from ..config import get_config, resolve_workspace

    if isinstance(layout, Path):
        # Backward compatibility for tests passing a Path root
        layout = resolve_workspace(target_override=layout)

    cfg = get_config()

    target = layout.target_dir
    vaultspec = layout.vaultspec_dir

    ROOT_DIR = target
    TARGET_DIR = target
    RULES_SRC_DIR = vaultspec / Resource.RULES.value / Resource.RULES.value
    SKILLS_SRC_DIR = vaultspec / Resource.RULES.value / Resource.SKILLS.value
    AGENTS_SRC_DIR = vaultspec / Resource.RULES.value / Resource.AGENTS.value
    SYSTEM_SRC_DIR = vaultspec / Resource.RULES.value / Resource.SYSTEM.value
    TEMPLATES_DIR = vaultspec / Resource.RULES.value / Resource.TEMPLATES.value
    FRAMEWORK_CONFIG_SRC = SYSTEM_SRC_DIR / FileName.FRAMEWORK.value
    PROJECT_CONFIG_SRC = SYSTEM_SRC_DIR / FileName.PROJECT.value
    HOOKS_DIR = vaultspec / Resource.RULES.value / Resource.HOOKS.value
    shared_agents_root = target / DirName.ANTIGRAVITY.value

    # Build Tool Configurations
    TOOL_CONFIGS = {
        Tool.CLAUDE: _create_tool_cfg(
            Tool.CLAUDE, target, cfg.claude_dir, config=FileName.CLAUDE
        ),
        Tool.GEMINI: _create_tool_cfg(
            Tool.GEMINI,
            target,
            cfg.gemini_dir,
            config=FileName.GEMINI,
            system="SYSTEM.md",
        ),
        Tool.ANTIGRAVITY: ToolConfig(
            name=Tool.ANTIGRAVITY.value,
            rules_dir=shared_agents_root / Resource.RULES.value,
            skills_dir=shared_agents_root / Resource.SKILLS.value,
            agents_dir=None,
            config_file=target / FileName.GEMINI.value,
            rule_ref_dir=shared_agents_root / Resource.RULES.value,
            system_file=None,
            emit_system_rule=False,
        ),
        Tool.CODEX: ToolConfig(
            name=Tool.CODEX.value,
            rules_dir=None,
            skills_dir=shared_agents_root / Resource.SKILLS.value,
            agents_dir=None,
            config_file=None,
            native_config_file=(
                target / DirName.CODEX.value / FileName.CONFIG_TOML.value
            ),
            rule_ref_dir=None,
            system_file=None,
            emit_system_rule=False,
        ),
    }
