"""Multi-resource manager for .vaultspec/ framework.

Manages rules, agents, and skills across tool-specific destinations
(Claude, Gemini, Antigravity) with format-aware frontmatter transformations
and tier-based model resolution.

Usage:
    python .vaultspec/scripts/cli.py <resource> <command> [options]
    python .vaultspec/scripts/cli.py sync-all [--prune] [--dry-run]
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from collections.abc import Callable

# ---------------------------------------------------------------------------
# YAML parsing: prefer PyYAML, fall back to simple parser
# ---------------------------------------------------------------------------
try:
    import yaml

    def _yaml_load(text: str) -> dict[str, Any]:
        return yaml.safe_load(text) or {}

    def _yaml_dump(data: dict[str, Any]) -> str:
        return yaml.dump(
            data, default_flow_style=False, allow_unicode=True, sort_keys=False
        ).rstrip("\n")

except ImportError:
    yaml = None  # type: ignore

    def _yaml_load(text: str) -> dict[str, Any]:
        """Minimal 2-level YAML parser."""
        data: dict[str, Any] = {}
        current_key: str | None = None
        for line in text.splitlines():
            if not line.strip():
                continue
            # Indented line -> nested under current_key
            if line.startswith("  ") and current_key is not None:
                stripped = line.strip()
                if ":" in stripped:
                    k, v = stripped.split(":", 1)
                    if not isinstance(data[current_key], dict):
                        data[current_key] = {}
                    data[current_key][k.strip()] = v.strip()
                continue
            # Top-level key
            if ":" in line:
                k, v = line.split(":", 1)
                k = k.strip()
                v = v.strip()
                if v:
                    # Strip quotes
                    if (v.startswith('"') and v.endswith('"')) or (
                        v.startswith("'") and v.endswith("'")
                    ):
                        v = v[1:-1]
                    data[k] = v
                else:
                    data[k] = {}
                current_key = k
        return data

    def _yaml_dump(data: dict[str, Any]) -> str:
        """Minimal YAML serializer."""
        lines: list[str] = []
        for k, v in data.items():
            if isinstance(v, dict):
                lines.append(f"{k}:")
                for sk, sv in v.items():
                    lines.append(f"  {sk}: {sv}")
            elif isinstance(v, str) and (
                ":" in v or '"' in v or "'" in v or v != v.strip()
            ):
                lines.append(f'{k}: "{v}"')
            else:
                lines.append(f"{k}: {v}")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Provider imports for tier-based model resolution
# ---------------------------------------------------------------------------
from _paths import LIB_SRC_DIR  # noqa: F401
from _paths import ROOT_DIR as _PATHS_ROOT_DIR  # shared path bootstrap

try:
    from protocol.providers.base import CapabilityLevel
    from protocol.providers.claude import ClaudeProvider
    from protocol.providers.gemini import GeminiProvider

    PROVIDERS: dict[str, Any] = {
        "claude": ClaudeProvider(),
        "gemini": GeminiProvider(),
    }
except ImportError:
    CapabilityLevel = None  # type: ignore
    PROVIDERS = {}
    print(
        "Warning: agent_providers not found. Tier resolution unavailable.",
        file=sys.stderr,
    )

# ---------------------------------------------------------------------------
# Path constants
# ---------------------------------------------------------------------------

PROTECTED_SKILLS = {"fd", "rg", "sg", "sd"}

# AUTO-GENERATED header
CONFIG_HEADER = "<!-- AUTO-GENERATED by cli.py config sync. -->"


@dataclass
class ToolConfig:
    name: str
    rules_dir: Path | None
    agents_dir: Path | None
    skills_dir: Path | None
    config_file: Path | None = None
    system_file: Path | None = None


# Module-level globals initialised by init_paths()
ROOT_DIR: Path = Path()
RULES_SRC_DIR: Path = Path()
RULES_CUSTOM_DIR: Path = Path()
AGENTS_SRC_DIR: Path = Path()
SKILLS_SRC_DIR: Path = Path()
SYSTEM_SRC_DIR: Path = Path()
FRAMEWORK_CONFIG_SRC: Path = Path()
PROJECT_CONFIG_SRC: Path = Path()
TOOL_CONFIGS: dict[str, ToolConfig] = {}


def init_paths(root: Path) -> None:
    """(Re-)initialise all path globals from *root*."""
    global ROOT_DIR, RULES_SRC_DIR, RULES_CUSTOM_DIR, AGENTS_SRC_DIR
    global SKILLS_SRC_DIR, SYSTEM_SRC_DIR
    global FRAMEWORK_CONFIG_SRC, PROJECT_CONFIG_SRC, TOOL_CONFIGS

    ROOT_DIR = root
    RULES_SRC_DIR = root / ".vaultspec" / "rules"
    RULES_CUSTOM_DIR = root / ".vaultspec" / "rules-custom"
    AGENTS_SRC_DIR = root / ".vaultspec" / "agents"
    SKILLS_SRC_DIR = root / ".vaultspec" / "skills"
    SYSTEM_SRC_DIR = root / ".vaultspec" / "system"
    FRAMEWORK_CONFIG_SRC = root / ".vaultspec" / "FRAMEWORK.md"
    PROJECT_CONFIG_SRC = root / ".vaultspec" / "PROJECT.md"

    # Backward compatibility: warn if old filenames still exist
    old_internal = root / ".vaultspec" / "INTERNAL.md"
    old_custom = root / ".vaultspec" / "CUSTOM.md"
    if old_internal.exists() and not FRAMEWORK_CONFIG_SRC.exists():
        print(
            "Warning: .vaultspec/INTERNAL.md is deprecated."
            " Rename to .vaultspec/FRAMEWORK.md",
            file=sys.stderr,
        )
    if old_custom.exists() and not PROJECT_CONFIG_SRC.exists():
        print(
            "Warning: .vaultspec/CUSTOM.md is deprecated."
            " Rename to .vaultspec/PROJECT.md",
            file=sys.stderr,
        )

    TOOL_CONFIGS = {
        "claude": ToolConfig(
            name="claude",
            rules_dir=root / ".claude" / "rules",
            agents_dir=root / ".claude" / "agents",
            skills_dir=root / ".claude" / "skills",
            config_file=root / ".claude" / "CLAUDE.md",
            system_file=None,
        ),
        "gemini": ToolConfig(
            name="gemini",
            rules_dir=root / ".gemini" / "rules",
            agents_dir=root / ".gemini" / "agents",
            skills_dir=root / ".gemini" / "skills",
            config_file=root / ".gemini" / "GEMINI.md",
            system_file=root / ".gemini" / "SYSTEM.md",
        ),
        "agents": ToolConfig(
            name="agents",
            rules_dir=None,
            agents_dir=None,
            skills_dir=None,
            config_file=root / "AGENTS.md",
            system_file=None,
        ),
        "antigravity": ToolConfig(
            name="antigravity",
            rules_dir=root / ".agent" / "rules",
            agents_dir=None,
            skills_dir=root / ".agent" / "skills",
            system_file=None,
        ),
    }


# Default initialisation
init_paths(_PATHS_ROOT_DIR)


@dataclass
class SyncResult:
    added: int = 0
    updated: int = 0
    skipped: int = 0
    pruned: int = 0
    errors: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Frontmatter utilities
# ---------------------------------------------------------------------------

from vault.parser import parse_frontmatter  # noqa: E402


def build_file(frontmatter: dict[str, Any], body: str) -> str:
    """Assemble a file from frontmatter dict and body content."""
    fm_str = _yaml_dump(frontmatter)
    return f"---\n{fm_str}\n---\n\n{body}"


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def atomic_write(path: Path, content: str) -> None:
    """Write content to file atomically via tmp + rename."""
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)


# ---------------------------------------------------------------------------
# Tier resolution
# ---------------------------------------------------------------------------


def resolve_model(tool: str, tier: str) -> str | None:
    """Resolve a capability tier name to a model string."""
    if CapabilityLevel is None or tool not in PROVIDERS:
        return None
    try:
        level = CapabilityLevel[tier.upper()]
    except (KeyError, AttributeError):
        return None
    return PROVIDERS[tool].get_best_model_for_capability(level)


# ---------------------------------------------------------------------------
# Rules handler
# ---------------------------------------------------------------------------


def collect_rules() -> dict[str, tuple[Path, dict[str, Any], str]]:
    """Collect rules from built-in + custom."""
    sources: dict[str, tuple[Path, dict[str, Any], str]] = {}

    for src_dir in [RULES_SRC_DIR, RULES_CUSTOM_DIR]:
        if not src_dir.exists():
            continue
        for f in sorted(src_dir.glob("*.md")):
            content = f.read_text(encoding="utf-8")
            meta, body = parse_frontmatter(content)
            sources[f.name] = (f, meta, body)

    return sources


def transform_rule(tool: str, name: str, _meta: dict[str, Any], body: str) -> str:
    """Transform a rule for a specific tool destination."""
    fm: dict[str, Any] = {}
    if tool != "antigravity":
        fm["name"] = Path(name).stem
    fm["trigger"] = "always_on"
    return build_file(fm, body)


def rules_list(_args: argparse.Namespace) -> None:
    print(f"{'Name':<40} {'Source':<15}")
    print("-" * 55)

    if RULES_SRC_DIR.exists():
        for f in sorted(RULES_SRC_DIR.glob("*.md")):
            print(f"{f.name:<40} {'Built-in':<15}")

    if RULES_CUSTOM_DIR.exists():
        for f in sorted(RULES_CUSTOM_DIR.glob("*.md")):
            print(f"{f.name:<40} {'Custom':<15}")


def rules_add(args: argparse.Namespace) -> None:
    ensure_dir(RULES_CUSTOM_DIR)

    file_name = args.name if args.name.endswith(".md") else f"{args.name}.md"
    file_path = RULES_CUSTOM_DIR / file_name

    if file_path.exists() and not args.force:
        print(f"Error: Rule '{file_name}' exists. Use --force to overwrite.")
        return

    content = args.content

    if not content:
        if sys.stdin.isatty():
            editor = os.environ.get("EDITOR", "zed -w")
            scaffold = f"---\nname: {args.name}\n---\n\n# Rule content\n"
            file_path.write_text(scaffold, encoding="utf-8")
            print(f"Opening editor ({editor}) for {file_path}...")
            try:
                subprocess.call([*editor.split(), str(file_path)])
                print(f"Rule saved to {file_path}")
            except Exception as e:
                print(f"Error opening editor: {e}")
            return
        else:
            content = sys.stdin.read()

    fm = {"name": args.name}
    full = build_file(fm, (content or "").lstrip())
    file_path.write_text(full, encoding="utf-8")
    print(f"Created custom rule: {file_path}")


def rules_sync(args: argparse.Namespace) -> None:
    sources = collect_rules()
    dry_run = getattr(args, "dry_run", False)
    prune = getattr(args, "prune", False)

    total = SyncResult()
    for tool_name, cfg in TOOL_CONFIGS.items():
        if cfg.rules_dir is None:
            continue
        result = sync_files(
            sources=sources,
            dest_dir=cfg.rules_dir,
            transform_fn=lambda _t, n, m, b, _tn=tool_name: transform_rule(
                _tn, n, m, b
            ),
            dest_path_fn=lambda dest_dir, name: dest_dir / name,
            prune=prune,
            dry_run=dry_run,
            label=f"rules -> {tool_name}",
        )
        total.added += result.added
        total.updated += result.updated
        total.pruned += result.pruned
        total.skipped += result.skipped
        total.errors.extend(result.errors)

    print_summary("Rules", total)


# ---------------------------------------------------------------------------
# Agents handler
# ---------------------------------------------------------------------------


def collect_agents() -> dict[str, tuple[Path, dict[str, Any], str]]:
    """Collect agent definitions from .vaultspec/agents/."""
    sources: dict[str, tuple[Path, dict[str, Any], str]] = {}
    if not AGENTS_SRC_DIR.exists():
        return sources
    for f in sorted(AGENTS_SRC_DIR.glob("*.md")):
        content = f.read_text(encoding="utf-8")
        meta, body = parse_frontmatter(content)
        sources[f.name] = (f, meta, body)
    return sources


def transform_agent(
    tool: str,
    name: str,
    meta: dict[str, Any],
    body: str,
    *,
    resolve_fn: Callable[..., str | None] | None = None,
) -> str | None:
    """Transform an agent for a specific tool destination."""
    agent_name = Path(name).stem
    description = meta.get("description", "")
    tier = meta.get("tier", "")

    if not tier:
        print(f"  Warning: Agent '{agent_name}' missing tier.", file=sys.stderr)
        return None

    _resolve = resolve_fn or resolve_model
    model = _resolve(tool, tier)
    if model is None:
        msg = f"  Warning: No model for {tool}/{tier}. Skipping {agent_name}."
        print(msg, file=sys.stderr)
        return None

    fm = {
        "name": agent_name,
        "description": description,
        "kind": "local",
        "model": model,
    }
    return build_file(fm, body)


def agents_list(_args: argparse.Namespace) -> None:
    sources = collect_agents()
    if not sources:
        print("No agents found.")
        return

    print(f"{'Name':<25} {'Tier':<8} {'Claude':<25} {'Gemini':<25}")
    print("-" * 83)
    for name, meta_tuple in sources.items():
        _path, meta, _body = meta_tuple
        agent_name = Path(name).stem
        tier = meta.get("tier", "?")
        claude_model = resolve_model("claude", tier) or "?"
        gemini_model = resolve_model("gemini", tier) or "?"
        print(f"{agent_name:<25} {tier:<8} {claude_model:<25} {gemini_model:<25}")


def agents_add(args: argparse.Namespace) -> None:
    ensure_dir(AGENTS_SRC_DIR)

    file_name = args.name if args.name.endswith(".md") else f"{args.name}.md"
    file_path = AGENTS_SRC_DIR / file_name

    if file_path.exists() and not getattr(args, "force", False):
        print(f"Error: Agent '{file_name}' exists. Use --force to overwrite.")
        return

    description = getattr(args, "description", "") or ""
    tier = getattr(args, "tier", "MEDIUM") or "MEDIUM"

    fm = {"description": description, "tier": tier.upper()}
    scaffold = build_file(
        fm, f"# Persona: {args.name}\n\nDefine your agent persona here.\n"
    )

    if sys.stdin.isatty():
        file_path.write_text(scaffold, encoding="utf-8")
        editor = os.environ.get("EDITOR", "zed -w")
        print(f"Opening editor ({editor}) for {file_path}...")
        try:
            subprocess.call([*editor.split(), str(file_path)])
            print(f"Agent saved to {file_path}")
        except Exception as e:
            print(f"Error opening editor: {e}")
    else:
        file_path.write_text(scaffold, encoding="utf-8")
        print(f"Created agent: {file_path}")


def agents_set_tier(args: argparse.Namespace) -> None:
    """Update the tier of an agent in its source file."""
    agent_name = args.name
    new_tier = args.tier.upper()

    if new_tier not in ("LOW", "MEDIUM", "HIGH"):
        print(f"Error: Invalid tier '{new_tier}'.")
        return

    file_name = agent_name if agent_name.endswith(".md") else f"{agent_name}.md"
    file_path = AGENTS_SRC_DIR / file_name

    if not file_path.exists():
        print(f"Error: Agent '{agent_name}' not found at {file_path}")
        return

    content = file_path.read_text(encoding="utf-8")
    meta, body = parse_frontmatter(content)
    old_tier = meta.get("tier", "?")
    meta["tier"] = new_tier

    atomic_write(file_path, build_file(meta, body))
    print(f"Updated {agent_name}: tier {old_tier} -> {new_tier}")

    # Show resolved models
    for tool_name in ["claude", "gemini"]:
        model = resolve_model(tool_name, new_tier)
        if model:
            print(f"  {tool_name}: {model}")

    print("Run 'agents sync' to propagate changes.")


def agents_sync(
    args: argparse.Namespace,
    *,
    resolve_fn: Callable[..., str | None] | None = None,
) -> None:
    sources = collect_agents()
    dry_run = getattr(args, "dry_run", False)
    prune = getattr(args, "prune", False)

    total = SyncResult()
    for tool_name, cfg in TOOL_CONFIGS.items():
        if cfg.agents_dir is None:
            continue
        result = sync_files(
            sources=sources,
            dest_dir=cfg.agents_dir,
            transform_fn=lambda _t, n, m, b, _tn=tool_name: transform_agent(
                _tn, n, m, b, resolve_fn=resolve_fn
            ),
            dest_path_fn=lambda dest_dir, name: dest_dir / name,
            prune=prune,
            dry_run=dry_run,
            label=f"agents -> {tool_name}",
        )
        total.added += result.added
        total.updated += result.updated
        total.pruned += result.pruned
        total.skipped += result.skipped
        total.errors.extend(result.errors)

    print_summary("Agents", total)


# ---------------------------------------------------------------------------
# Skills handler
# ---------------------------------------------------------------------------


def collect_skills() -> dict[str, tuple[Path, dict[str, Any], str]]:
    """Collect spec-* skill definitions from .vaultspec/skills/."""
    sources: dict[str, tuple[Path, dict[str, Any], str]] = {}
    if not SKILLS_SRC_DIR.exists():
        return sources
    for f in sorted(SKILLS_SRC_DIR.glob("spec-*.md")):
        content = f.read_text(encoding="utf-8")
        meta, body = parse_frontmatter(content)
        sources[f.stem] = (f, meta, body)
    return sources


def transform_skill(_tool: str, name: str, meta: dict[str, Any], body: str) -> str:
    """Transform a skill for a specific tool destination."""
    description = meta.get("description", "")
    fm = {"name": name, "description": description}
    return build_file(fm, body)


def skill_dest_path(dest_dir: Path, name: str) -> Path:
    """Skill destination is a directory with SKILL.md inside."""
    return dest_dir / name / "SKILL.md"


def skills_list(_args: argparse.Namespace) -> None:
    sources = collect_skills()
    if not sources:
        print("No managed skills found.")
        return

    print(f"{'Name':<30} {'Description':<60}")
    print("-" * 90)
    for name, meta_tuple in sources.items():
        _path, meta, _body = meta_tuple
        desc = meta.get("description", "")
        if len(desc) > 57:
            desc = desc[:57] + "..."
        print(f"{name:<30} {desc:<60}")


def skills_add(args: argparse.Namespace) -> None:
    ensure_dir(SKILLS_SRC_DIR)

    skill_name = args.name
    if not skill_name.startswith("spec-"):
        skill_name = f"spec-{skill_name}"
    file_name = f"{skill_name}.md"
    file_path = SKILLS_SRC_DIR / file_name

    if file_path.exists() and not getattr(args, "force", False):
        print(f"Error: Skill '{file_name}' exists. Use --force to overwrite.")
        return

    description = getattr(args, "description", "") or ""
    fm = {"description": description}
    scaffold = build_file(
        fm, f"# {skill_name}\n\nDefine your skill instructions here.\n"
    )

    if sys.stdin.isatty():
        file_path.write_text(scaffold, encoding="utf-8")
        editor = os.environ.get("EDITOR", "zed -w")
        print(f"Opening editor ({editor}) for {file_path}...")
        try:
            subprocess.call([*editor.split(), str(file_path)])
            print(f"Skill saved to {file_path}")
        except Exception as e:
            print(f"Error opening editor: {e}")
    else:
        file_path.write_text(scaffold, encoding="utf-8")
        print(f"Created skill: {file_path}")


def skills_sync(args: argparse.Namespace) -> None:
    sources = collect_skills()
    dry_run = getattr(args, "dry_run", False)
    prune = getattr(args, "prune", False)

    total = SyncResult()
    for tool_name, cfg in TOOL_CONFIGS.items():
        if cfg.skills_dir is None:
            continue
        result = sync_skills(
            sources=sources,
            skills_dir=cfg.skills_dir,
            transform_fn=lambda _t, n, m, b, _tn=tool_name: transform_skill(
                _tn, n, m, b
            ),
            prune=prune,
            dry_run=dry_run,
            label=f"skills -> {tool_name}",
        )
        total.added += result.added
        total.updated += result.updated
        total.pruned += result.pruned
        total.skipped += result.skipped
        total.errors.extend(result.errors)

    print_summary("Skills", total)


# ---------------------------------------------------------------------------
# Sync engine
# ---------------------------------------------------------------------------


def sync_files(
    sources: dict[str, tuple[Path, dict[str, Any], str]],
    dest_dir: Path,
    transform_fn,
    dest_path_fn,
    prune: bool,
    dry_run: bool,
    label: str,
) -> SyncResult:
    """Sync source files to a destination directory."""
    result = SyncResult()
    ensure_dir(dest_dir)

    print(f"  Syncing {label}...")

    for name, meta_tuple in sources.items():
        _src_path, meta, body = meta_tuple
        dest_path = dest_path_fn(dest_dir, name)
        try:
            content = transform_fn(None, name, meta, body)
            if content is None:
                result.skipped += 1
                continue

            action = "[UPDATE]" if dest_path.exists() else "[ADD]"

            if dry_run:
                rel = dest_path.relative_to(ROOT_DIR)
                print(f"    {action} {rel}")
            else:
                ensure_dir(dest_path.parent)
                atomic_write(dest_path, content)

            if action == "[ADD]":
                result.added += 1
            else:
                result.updated += 1

        except Exception as e:
            result.errors.append(f"{name}: {e}")
            print(f"    [ERROR] {name}: {e}", file=sys.stderr)

    # Prune
    if prune:
        source_names = set(sources.keys())
        if dest_dir.exists():
            for existing in dest_dir.glob("*.md"):
                if existing.name not in source_names:
                    rel = existing.relative_to(ROOT_DIR)
                    if dry_run:
                        print(f"    [PRUNE] {rel}")
                    else:
                        existing.unlink()
                    result.pruned += 1

    return result


def sync_skills(
    sources: dict[str, tuple[Path, dict[str, Any], str]],
    skills_dir: Path,
    transform_fn,
    prune: bool,
    dry_run: bool,
    label: str,
) -> SyncResult:
    """Sync skill files to a destination skills directory."""
    result = SyncResult()
    ensure_dir(skills_dir)

    print(f"  Syncing {label}...")

    for name, meta_tuple in sources.items():
        _src_path, meta, body = meta_tuple
        dest_path = skill_dest_path(skills_dir, name)
        try:
            content = transform_fn(None, name, meta, body)
            if content is None:
                result.skipped += 1
                continue

            action = "[UPDATE]" if dest_path.exists() else "[ADD]"

            if dry_run:
                rel = dest_path.relative_to(ROOT_DIR)
                print(f"    {action} {rel}")
            else:
                ensure_dir(dest_path.parent)
                atomic_write(dest_path, content)

            if action == "[ADD]":
                result.added += 1
            else:
                result.updated += 1

        except Exception as e:
            result.errors.append(f"{name}: {e}")
            print(f"    [ERROR] {name}: {e}", file=sys.stderr)

    # Prune: only prune spec-* prefixed skill dirs
    if prune:
        source_names = set(sources.keys())
        if skills_dir.exists():
            for skill_subdir in skills_dir.iterdir():
                if not skill_subdir.is_dir():
                    continue
                if skill_subdir.name in PROTECTED_SKILLS:
                    continue
                if not skill_subdir.name.startswith("spec-"):
                    continue
                if skill_subdir.name not in source_names:
                    skill_md = skill_subdir / "SKILL.md"
                    if skill_md.exists():
                        rel = skill_md.relative_to(ROOT_DIR)
                        if dry_run:
                            print(f"    [PRUNE] {rel}")
                        else:
                            skill_md.unlink()
                            if not any(skill_subdir.iterdir()):
                                skill_subdir.rmdir()
                        result.pruned += 1

    return result


# ---------------------------------------------------------------------------
# Config handler (CLAUDE.md / GEMINI.md / AGENTS.md generation)
# ---------------------------------------------------------------------------


def _collect_rule_refs(cfg: ToolConfig) -> list[str]:
    """Collect rule file references."""
    if cfg.rules_dir is None or cfg.config_file is None:
        if cfg.name == "agents" and cfg.config_file:
            config_dir = cfg.config_file.parent
            refs = []
            sources = collect_rules()
            for name in sorted(sources.keys()):
                src_path, _meta, _body = sources[name]
                try:
                    rel = src_path.relative_to(config_dir)
                    refs.append(str(rel).replace("\\", "/"))
                except ValueError:
                    ref = src_path.relative_to(ROOT_DIR)
                    refs.append(str(ref).replace("\\", "/"))
            return refs
        return []
    if not cfg.rules_dir.exists():
        return []

    config_dir = cfg.config_file.parent
    refs = []
    for rule_file in sorted(cfg.rules_dir.glob("*.md")):
        try:
            rel = rule_file.relative_to(config_dir)
            refs.append(str(rel).replace("\\", "/"))
        except ValueError:
            ref = rule_file.relative_to(ROOT_DIR)
            refs.append(str(ref).replace("\\", "/"))
    return refs


def _generate_config(cfg: ToolConfig) -> str | None:
    """Generate config file content."""
    if not FRAMEWORK_CONFIG_SRC.exists():
        return None

    internal_body = FRAMEWORK_CONFIG_SRC.read_text(encoding="utf-8").strip()
    custom_body = (
        PROJECT_CONFIG_SRC.read_text(encoding="utf-8").strip()
        if PROJECT_CONFIG_SRC.exists()
        else ""
    )

    fm = {"system_framework": internal_body}

    # Body starts with custom content
    body_parts = []
    if custom_body:
        body_parts.append(custom_body)

    # Add rules
    refs = _collect_rule_refs(cfg)
    if refs:
        if body_parts:
            body_parts.append("")
        body_parts.append("## Rules")
        body_parts.append("")
        body_parts.append("You MUST respect these rules at all times:")
        body_parts.append("")
        for ref in refs:
            body_parts.append(f"@{ref}")

    body = "\n".join(body_parts)
    return f"{CONFIG_HEADER}\n{build_file(fm, body)}"


def _is_cli_managed(path: Path) -> bool:
    """Check if a config file was generated by this CLI."""
    if not path.exists():
        return False
    try:
        content = path.read_text(encoding="utf-8")
        return content.startswith(CONFIG_HEADER)
    except Exception:
        return False


def config_show(_args: argparse.Namespace) -> None:
    """Display internal/custom content and references."""
    if not FRAMEWORK_CONFIG_SRC.exists():
        rel = FRAMEWORK_CONFIG_SRC.relative_to(ROOT_DIR)
        print(f"No framework config found at {rel}")
        return

    print(f"Framework: {FRAMEWORK_CONFIG_SRC.relative_to(ROOT_DIR)}")
    print("-" * 60)
    print(FRAMEWORK_CONFIG_SRC.read_text(encoding="utf-8").strip())
    print("-" * 60)

    if PROJECT_CONFIG_SRC.exists():
        print(f"Project: {PROJECT_CONFIG_SRC.relative_to(ROOT_DIR)}")
        print("-" * 60)
        print(PROJECT_CONFIG_SRC.read_text(encoding="utf-8").strip())
        print("-" * 60)

    print("Generated references per tool:")
    for tool_name, cfg in TOOL_CONFIGS.items():
        if cfg.config_file is None:
            continue
        refs = _collect_rule_refs(cfg)
        dest_rel = cfg.config_file.relative_to(ROOT_DIR)
        managed = "CLI-managed" if _is_cli_managed(cfg.config_file) else "custom"
        print(f"\n  {tool_name} ({dest_rel}) [{managed}]:")
        if refs:
            for ref in refs:
                print(f"    @{ref}")
        else:
            print("    (no rules synced yet)")


def config_sync(args: argparse.Namespace) -> None:
    """Sync internal and custom configs to tool configs."""
    dry_run = getattr(args, "dry_run", False)
    force = getattr(args, "force", False)

    if not FRAMEWORK_CONFIG_SRC.exists():
        print("  Error: No framework config found at .vaultspec/FRAMEWORK.md")
        return

    result = SyncResult()

    for _tool_name, cfg in TOOL_CONFIGS.items():
        if cfg.config_file is None:
            continue

        content = _generate_config(cfg)
        if content is None:
            result.skipped += 1
            continue

        rel = cfg.config_file.relative_to(ROOT_DIR)

        # Safety guard
        if (
            cfg.config_file.exists()
            and not _is_cli_managed(cfg.config_file)
            and not force
        ):
            print(f"    [SKIP] {rel} - file exists with custom content.")
            msg = "           Migrate to .vaultspec/PROJECT.md, then --force."
            print(msg)
            result.skipped += 1
            continue

        action = "[UPDATE]" if cfg.config_file.exists() else "[ADD]"

        if dry_run:
            print(f"    {action} {rel}")
        else:
            ensure_dir(cfg.config_file.parent)
            atomic_write(cfg.config_file, content)

        if action == "[ADD]":
            result.added += 1
        else:
            result.updated += 1

    print_summary("Config", result)


# ---------------------------------------------------------------------------
# System prompt handler
# ---------------------------------------------------------------------------


def collect_system_parts() -> dict[str, tuple[Path, dict[str, Any], str]]:
    """Collect system prompt parts from .vaultspec/system/."""
    sources: dict[str, tuple[Path, dict[str, Any], str]] = {}
    if not SYSTEM_SRC_DIR.exists():
        return sources
    for f in sorted(SYSTEM_SRC_DIR.glob("*.md")):
        content = f.read_text(encoding="utf-8")
        meta, body = parse_frontmatter(content)
        sources[f.stem] = (f, meta, body)
    return sources


def _collect_agent_listing() -> str:
    """Build a markdown section listing available agents."""
    agents = collect_agents()
    if not agents:
        return ""
    lines = [
        "## Available Sub-Agents",
        "",
        "Sub-agents are specialized expert agents available in `.vaultspec/agents/`.",
        "Dispatch using the `spec-subagent` skill.",
        "",
    ]
    for name, meta_tuple in agents.items():
        _path, meta, _body = meta_tuple
        agent_name = Path(name).stem
        tier = meta.get("tier", "?")
        description = meta.get("description", "")
        lines.append(f"- **{agent_name}** ({tier}): {description}")
    return "\n".join(lines)


def _collect_skill_listing() -> str:
    """Build a markdown section listing available skills."""
    skills = collect_skills()
    if not skills:
        return ""
    lines = [
        "## Available Skills",
        "",
    ]
    for name, meta_tuple in skills.items():
        _path, meta, _body = meta_tuple
        description = meta.get("description", "")
        lines.append(f"- **{name}**: {description}")
    return "\n".join(lines)


def _generate_system_prompt(cfg: ToolConfig) -> str | None:
    """Assemble system prompt for a tool from .vaultspec/system/ parts."""
    if cfg.system_file is None:
        return None

    parts = collect_system_parts()
    if not parts:
        return None

    assembled: list[str] = [CONFIG_HEADER]

    # 1. base.md body first
    if "base" in parts:
        _path, _meta, body = parts["base"]
        assembled.append(body)

    # 2. Tool-specific parts (where meta "tool" matches cfg.name)
    for name, (_path, meta, body) in sorted(parts.items()):
        if name == "base":
            continue
        tool_filter = meta.get("tool")
        if tool_filter is not None and tool_filter == cfg.name:
            assembled.append(body)

    # 3. Auto-generated agent listing
    agent_listing = _collect_agent_listing()
    if agent_listing:
        assembled.append(agent_listing)

    # 4. Auto-generated skill listing
    skill_listing = _collect_skill_listing()
    if skill_listing:
        assembled.append(skill_listing)

    # 5. Remaining shared parts (no "tool" key, not "base") in sorted order
    for name, (_path, meta, body) in sorted(parts.items()):
        if name == "base":
            continue
        if meta.get("tool") is not None:
            continue
        assembled.append(body)

    return "\n\n".join(assembled)


def system_show(_args: argparse.Namespace) -> None:
    """Display system parts table and generation targets."""
    parts = collect_system_parts()
    if not parts:
        print("No system parts found in .vaultspec/system/")
        return

    print(f"{'Name':<25} {'Tool Filter':<15} {'Lines':<8}")
    print("-" * 48)
    for name, (_path, meta, body) in sorted(parts.items()):
        tool_filter = meta.get("tool", "-")
        line_count = len(body.strip().splitlines()) if body.strip() else 0
        print(f"{name:<25} {tool_filter:<15} {line_count:<8}")

    print("\nGeneration targets:")
    for tool_name, cfg in TOOL_CONFIGS.items():
        if cfg.system_file is None:
            continue
        rel = cfg.system_file.relative_to(ROOT_DIR)
        managed = "CLI-managed" if _is_cli_managed(cfg.system_file) else "custom"
        print(f"  {tool_name}: {rel} [{managed}]")


def system_sync(args: argparse.Namespace) -> None:
    """Sync assembled system prompts to tool destinations."""
    dry_run = getattr(args, "dry_run", False)
    force = getattr(args, "force", False)

    result = SyncResult()

    for _tool_name, cfg in TOOL_CONFIGS.items():
        if cfg.system_file is None:
            continue

        content = _generate_system_prompt(cfg)
        if content is None:
            result.skipped += 1
            continue

        rel = cfg.system_file.relative_to(ROOT_DIR)

        # Safety guard
        if (
            cfg.system_file.exists()
            and not _is_cli_managed(cfg.system_file)
            and not force
        ):
            print(f"    [SKIP] {rel} - file exists with custom content.")
            print("           Use --force to overwrite.")
            result.skipped += 1
            continue

        action = "[UPDATE]" if cfg.system_file.exists() else "[ADD]"

        if dry_run:
            print(f"    {action} {rel}")
        else:
            ensure_dir(cfg.system_file.parent)
            atomic_write(cfg.system_file, content)

        if action == "[ADD]":
            result.added += 1
        else:
            result.updated += 1

    print_summary("System", result)


def print_summary(resource: str, result: SyncResult) -> None:
    parts = []
    if result.added:
        parts.append(f"{result.added} added")
    if result.updated:
        parts.append(f"{result.updated} updated")
    if result.pruned:
        parts.append(f"{result.pruned} pruned")
    if result.skipped:
        parts.append(f"{result.skipped} skipped")
    if result.errors:
        parts.append(f"{len(result.errors)} errors")
    summary = ", ".join(parts) if parts else "no changes"
    print(f"  {resource}: {summary}")


# ---------------------------------------------------------------------------
# Test runner
# ---------------------------------------------------------------------------

VALID_CATEGORIES = {"all", "unit", "api", "search", "index", "quality"}

MODULE_PATHS = {
    "cli": [".vaultspec/tests/cli"],
    "rag": [".vaultspec/tests/rag", ".vaultspec/lib/src/rag/tests"],
    "vault": [".vaultspec/lib/src/vault/tests"],
    "protocol": [".vaultspec/lib/src/protocol/tests"],
    "orchestration": [".vaultspec/lib/src/orchestration/tests"],
    "subagent": [
        ".vaultspec/tests/subagent",
        ".vaultspec/lib/src/subagent_server/tests",
    ],
}


def test_run(args: argparse.Namespace) -> None:
    category = getattr(args, "category", "all") or "all"
    module = getattr(args, "module", None)
    extra = getattr(args, "extra_args", []) or []

    cmd = [sys.executable, "-m", "pytest"]

    if category != "all":
        cmd.extend(["-m", category])

    if module:
        if module not in MODULE_PATHS:
            valid = ", ".join(sorted(MODULE_PATHS))
            print(f"Error: Unknown module '{module}'. Valid: {valid}")
            return
        for p in MODULE_PATHS[module]:
            cmd.append(str(ROOT_DIR / p))
    else:
        cmd.append(str(ROOT_DIR / ".vaultspec" / "tests"))
        cmd.append(str(ROOT_DIR / ".vaultspec" / "lib" / "src"))

    cmd.extend(extra)

    print(f"Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=str(ROOT_DIR))
    sys.exit(result.returncode)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def add_sync_flags(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--prune", action="store_true", help="Remove unknown files")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Manage rules, agents, and skills across tool destinations.",
        prog="cli.py",
    )
    parser.add_argument(
        "--root", type=Path, default=None, help="Override workspace root"
    )
    resource_parsers = parser.add_subparsers(dest="resource", help="Type")

    # --- rules ---
    rules_parser = resource_parsers.add_parser("rules", help="Manage rules")
    rules_sub = rules_parser.add_subparsers(dest="command")

    rules_sub.add_parser("list", help="List all rules")

    rules_add_parser = rules_sub.add_parser("add", help="Add a custom rule")
    rules_add_parser.add_argument("--name", required=True, help="Rule name")
    rules_add_parser.add_argument("--content", help="Rule content")
    rules_add_parser.add_argument("--force", action="store_true", help="Overwrite")

    rules_sync_parser = rules_sub.add_parser("sync", help="Sync rules")
    add_sync_flags(rules_sync_parser)

    # --- agents ---
    agents_parser = resource_parsers.add_parser("agents", help="Manage agents")
    agents_sub = agents_parser.add_subparsers(dest="command")

    agents_sub.add_parser("list", help="List all agents")

    agents_add_parser = agents_sub.add_parser("add", help="Add a new agent")
    agents_add_parser.add_argument("--name", required=True, help="Agent name")
    agents_add_parser.add_argument(
        "--description", default="", help="Agent description"
    )
    agents_add_parser.add_argument(
        "--tier",
        default="MEDIUM",
        choices=["LOW", "MEDIUM", "HIGH"],
        help="Capability tier",
    )
    agents_add_parser.add_argument("--force", action="store_true", help="Overwrite")

    agents_sync_parser = agents_sub.add_parser("sync", help="Sync agents")
    add_sync_flags(agents_sync_parser)

    agents_tier_parser = agents_sub.add_parser("set-tier", help="Update agent tier")
    agents_tier_parser.add_argument("name", help="Agent name")
    agents_tier_parser.add_argument(
        "--tier", required=True, choices=["LOW", "MEDIUM", "HIGH"], help="Tier"
    )

    # --- skills ---
    skills_parser = resource_parsers.add_parser("skills", help="Manage skills")
    skills_sub = skills_parser.add_subparsers(dest="command")

    skills_sub.add_parser("list", help="List all managed skills")

    skills_add_parser = skills_sub.add_parser("add", help="Add a new skill")
    skills_add_parser.add_argument("--name", required=True, help="Skill name")
    skills_add_parser.add_argument(
        "--description", default="", help="Skill description"
    )
    skills_add_parser.add_argument("--force", action="store_true", help="Overwrite")

    skills_sync_parser = skills_sub.add_parser("sync", help="Sync skills")
    add_sync_flags(skills_sync_parser)

    # --- config ---
    config_parser = resource_parsers.add_parser(
        "config", help="Manage tool configs (CLAUDE.md, GEMINI.md)"
    )
    config_sub = config_parser.add_subparsers(dest="command")

    config_sub.add_parser("show", help="Display internal/custom content")

    config_sync_parser = config_sub.add_parser("sync", help="Sync configs")
    add_sync_flags(config_sync_parser)
    config_sync_parser.add_argument(
        "--force", action="store_true", help="Overwrite custom content"
    )

    # --- system ---
    system_parser = resource_parsers.add_parser("system", help="Manage system prompts")
    system_sub = system_parser.add_subparsers(dest="command")

    system_sub.add_parser("show", help="Display system parts and targets")

    system_sync_parser = system_sub.add_parser("sync", help="Sync system prompts")
    add_sync_flags(system_sync_parser)
    system_sync_parser.add_argument(
        "--force", action="store_true", help="Overwrite custom content"
    )

    # --- sync-all ---
    sync_all_parser = resource_parsers.add_parser("sync-all", help="Sync all")
    add_sync_flags(sync_all_parser)
    sync_all_parser.add_argument("--force", action="store_true", help="Force overwrite")

    # --- test ---
    test_parser = resource_parsers.add_parser("test", help="Run tests")
    test_parser.add_argument(
        "category",
        nargs="?",
        default="all",
        choices=["all", "unit", "api", "search", "index", "quality"],
        help="Test category (default: all)",
    )
    test_parser.add_argument(
        "--module",
        "-m",
        choices=["cli", "rag", "vault", "protocol", "orchestration", "subagent"],
        help="Filter by module",
    )
    test_parser.add_argument("extra_args", nargs="*", help="Extra pytest arguments")

    args = parser.parse_args()

    if args.root is not None:
        init_paths(args.root.resolve())

    if args.resource == "rules":
        if args.command == "list":
            rules_list(args)
        elif args.command == "add":
            rules_add(args)
        elif args.command == "sync":
            rules_sync(args)
        else:
            rules_parser.print_help()
    elif args.resource == "agents":
        if args.command == "list":
            agents_list(args)
        elif args.command == "add":
            agents_add(args)
        elif args.command == "sync":
            agents_sync(args)
        elif args.command == "set-tier":
            agents_set_tier(args)
        else:
            agents_parser.print_help()
    elif args.resource == "skills":
        if args.command == "list":
            skills_list(args)
        elif args.command == "add":
            skills_add(args)
        elif args.command == "sync":
            skills_sync(args)
        else:
            skills_parser.print_help()
    elif args.resource == "config":
        if args.command == "show":
            config_show(args)
        elif args.command == "sync":
            config_sync(args)
        else:
            config_parser.print_help()
    elif args.resource == "system":
        if args.command == "show":
            system_show(args)
        elif args.command == "sync":
            system_sync(args)
        else:
            system_parser.print_help()
    elif args.resource == "test":
        test_run(args)
    elif args.resource == "sync-all":
        print("Syncing all resources...")
        rules_sync(args)
        agents_sync(args)
        skills_sync(args)
        system_sync(args)
        config_sync(args)
        print("Done.")
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
