# Lychee configuration
exclude = [
  '\[\[.*\]\]',
  "https://www.npmjs.com/.*",
  "https://github.com/.*",
  "https://www.linuxfoundation.org/.*",
  "https://gpui.rs/.*",
  "https://medium.com/.*",
  "https://skillsmp.com/.*",
  "https://www.iclr.cc/.*",
  "https://deepwiki.com/.*",
  "https://javascript.info/.*"
]
exclude_path = ["README.md"]
verbose = "info"
no_progress = true
accept = [200, 403, 410, 429, 502]
