"""Core types, path globals, and initialization helpers for vaultspec resource
management."""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# AUTO-GENERATED header constant
CONFIG_HEADER = "<!-- AUTO-GENERATED by cli.py config sync. -->"

PROTECTED_SKILLS = {"fd", "rg", "sg", "sd"}


@dataclass
class ToolConfig:
    """Configuration for a single AI tool destination (e.g. claude, gemini).

    Attributes:
        name: Short identifier for the tool (e.g. ``"claude"``).
        rules_dir: Directory where synced rule files are written, or ``None``
            if the tool does not use rules files.
        agents_dir: Directory where synced agent files are written, or ``None``
            if the tool does not use agent files.
        skills_dir: Directory where synced skill files are written, or ``None``
            if the tool does not use skill files.
        config_file: Path to the tool's main config file (e.g. ``CLAUDE.md``),
            or ``None`` if not applicable.
        system_file: Path to the tool's system prompt file, or ``None`` if the
            tool does not have a dedicated system file.
    """

    name: str
    rules_dir: Path | None
    agents_dir: Path | None
    skills_dir: Path | None
    config_file: Path | None = None
    system_file: Path | None = None


@dataclass
class SyncResult:
    """Accumulator for file synchronization statistics.

    Attributes:
        added: Number of files newly created at the destination.
        updated: Number of existing files that were overwritten.
        skipped: Number of files that were intentionally not written
            (e.g. transform returned ``None``, or safety guard triggered).
        pruned: Number of stale destination files that were deleted.
        errors: List of error message strings for files that failed to sync.
    """

    added: int = 0
    updated: int = 0
    skipped: int = 0
    pruned: int = 0
    errors: list[str] = field(default_factory=list)


# Module-level globals initialised by init_paths()
ROOT_DIR: Path = Path()
RULES_SRC_DIR: Path = Path()
AGENTS_SRC_DIR: Path = Path()
SKILLS_SRC_DIR: Path = Path()
SYSTEM_SRC_DIR: Path = Path()
TEMPLATES_DIR: Path = Path()
FRAMEWORK_CONFIG_SRC: Path = Path()
PROJECT_CONFIG_SRC: Path = Path()
HOOKS_DIR: Path = Path()
TOOL_CONFIGS: dict[Tool, ToolConfig] = {}

from ..protocol.providers import ClaudeProvider, GeminiProvider  # noqa: E402
from .enums import DirName, FileName, Resource, Tool

PROVIDERS: dict[str, Any] = {
    Tool.CLAUDE.value: ClaudeProvider(),
    Tool.GEMINI.value: GeminiProvider(),
}


def _create_tool_cfg(
    tool: Tool,
    root: Path,
    tool_dir: str | None = None,
    rules: bool = True,
    agents: bool = True,
    skills: bool = True,
    config: FileName | None = None,
    system: FileName | str | None = None,
) -> ToolConfig:
    """Helper to create a ToolConfig with standard directory patterns."""
    t_dir = root / tool_dir if tool_dir else None
    return ToolConfig(
        name=tool.value,
        rules_dir=t_dir / Resource.RULES.value if t_dir and rules else None,
        agents_dir=t_dir / Resource.AGENTS.value if t_dir and agents else None,
        skills_dir=t_dir / Resource.SKILLS.value if t_dir and skills else None,
        config_file=(t_dir / config.value) if t_dir and config else None,
        system_file=(
            (t_dir / (system.value if isinstance(system, FileName) else system))
            if t_dir and system
            else None
        ),
    )


def init_paths(layout: Any) -> None:
    """(Re-)initialise all path globals from a workspace layout.

    Accepts either a ``WorkspaceLayout`` (preferred) or a plain ``Path`` for
    backwards compatibility (treated as the output root with content located at
    ``root / framework_dir``).

    Args:
        layout: A ``WorkspaceLayout`` instance providing ``output_root`` and
            ``content_root`` attributes, or a ``Path`` used as the output root.
    """
    global ROOT_DIR, RULES_SRC_DIR, AGENTS_SRC_DIR
    global SKILLS_SRC_DIR, SYSTEM_SRC_DIR, TEMPLATES_DIR
    global FRAMEWORK_CONFIG_SRC, PROJECT_CONFIG_SRC
    global HOOKS_DIR, TOOL_CONFIGS

    from ..config import get_config

    cfg = get_config()

    if isinstance(layout, Path):
        # Legacy path: treat as output root, derive content from it
        root = layout
        content = root / cfg.framework_dir
    else:
        root = layout.output_root
        content = layout.content_root

    ROOT_DIR = root
    RULES_SRC_DIR = content / Resource.RULES.value / Resource.RULES.value
    AGENTS_SRC_DIR = content / Resource.RULES.value / Resource.AGENTS.value
    SKILLS_SRC_DIR = content / Resource.RULES.value / Resource.SKILLS.value
    SYSTEM_SRC_DIR = content / Resource.RULES.value / Resource.SYSTEM.value
    TEMPLATES_DIR = content / Resource.RULES.value / Resource.TEMPLATES.value
    FRAMEWORK_CONFIG_SRC = SYSTEM_SRC_DIR / FileName.FRAMEWORK.value
    PROJECT_CONFIG_SRC = SYSTEM_SRC_DIR / FileName.PROJECT.value
    HOOKS_DIR = content / Resource.RULES.value / Resource.HOOKS.value

    # Build Tool Configurations
    TOOL_CONFIGS = {
        Tool.CLAUDE: _create_tool_cfg(
            Tool.CLAUDE, root, cfg.claude_dir, config=FileName.CLAUDE
        ),
        Tool.GEMINI: _create_tool_cfg(
            Tool.GEMINI, root, cfg.gemini_dir, config=FileName.GEMINI, system="SYSTEM.md"
        ),
        Tool.AGENTS: ToolConfig(
            name=Tool.AGENTS.value,
            rules_dir=None,
            agents_dir=None,
            skills_dir=None,
            config_file=root / FileName.AGENTS.value,
            system_file=None,
        ),
        Tool.ANTIGRAVITY: _create_tool_cfg(
            Tool.ANTIGRAVITY,
            root,
            cfg.agent_dir,
            agents=False,
        ),
    }
