"""Core types, path globals, and initialization helpers for vaultspec resource
management."""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# AUTO-GENERATED header constant
CONFIG_HEADER = "<!-- AUTO-GENERATED by cli.py config sync. -->"

PROTECTED_SKILLS = {"fd", "rg", "sg", "sd"}


@dataclass
class ToolConfig:
    """Configuration for a single AI tool destination (e.g. claude, gemini).

    Attributes:
        name: Short identifier for the tool (e.g. ``"claude"``).
        rules_dir: Directory where synced rule files are written, or ``None``
            if the tool does not use rules files.
        agents_dir: Directory where synced agent files are written, or ``None``
            if the tool does not use agent files.
        skills_dir: Directory where synced skill files are written, or ``None``
            if the tool does not use skill files.
        config_file: Path to the tool's main config file (e.g. ``CLAUDE.md``),
            or ``None`` if not applicable.
        system_file: Path to the tool's system prompt file, or ``None`` if the
            tool does not have a dedicated system file.
    """

    name: str
    rules_dir: Path | None
    agents_dir: Path | None
    skills_dir: Path | None
    config_file: Path | None = None
    system_file: Path | None = None


@dataclass
class SyncResult:
    """Accumulator for file synchronization statistics.

    Attributes:
        added: Number of files newly created at the destination.
        updated: Number of existing files that were overwritten.
        skipped: Number of files that were intentionally not written
            (e.g. transform returned ``None``, or safety guard triggered).
        pruned: Number of stale destination files that were deleted.
        errors: List of error message strings for files that failed to sync.
    """

    added: int = 0
    updated: int = 0
    skipped: int = 0
    pruned: int = 0
    errors: list[str] = field(default_factory=list)


# Module-level globals initialised by init_paths()
ROOT_DIR: Path = Path()
RULES_SRC_DIR: Path = Path()
AGENTS_SRC_DIR: Path = Path()
SKILLS_SRC_DIR: Path = Path()
SYSTEM_SRC_DIR: Path = Path()
TEMPLATES_DIR: Path = Path()
FRAMEWORK_CONFIG_SRC: Path = Path()
PROJECT_CONFIG_SRC: Path = Path()
HOOKS_DIR: Path = Path()
TOOL_CONFIGS: dict[str, ToolConfig] = {}

from ..protocol.providers import ClaudeProvider, GeminiProvider  # noqa: E402

PROVIDERS: dict[str, Any] = {
    "claude": ClaudeProvider(),
    "gemini": GeminiProvider(),
}


def init_paths(layout: Any) -> None:
    """(Re-)initialise all path globals from a workspace layout.

    Accepts either a ``WorkspaceLayout`` (preferred) or a plain ``Path`` for
    backwards compatibility (treated as the output root with content located at
    ``root / framework_dir``).

    Also emits deprecation warnings for legacy config filenames
    (``INTERNAL.md``, ``FRAMEWORK.md``, ``CUSTOM.md``, ``PROJECT.md``) if they
    exist and the new canonical paths do not.

    Args:
        layout: A ``WorkspaceLayout`` instance providing ``output_root`` and
            ``content_root`` attributes, or a ``Path`` used as the output root.
    """
    global ROOT_DIR, RULES_SRC_DIR, AGENTS_SRC_DIR
    global SKILLS_SRC_DIR, SYSTEM_SRC_DIR, TEMPLATES_DIR
    global FRAMEWORK_CONFIG_SRC, PROJECT_CONFIG_SRC
    global HOOKS_DIR, TOOL_CONFIGS

    from ..config import get_config

    cfg = get_config()

    if isinstance(layout, Path):
        # Legacy path: treat as output root, derive content from it
        root = layout
        content = root / cfg.framework_dir
    else:
        root = layout.output_root
        content = layout.content_root

    ROOT_DIR = root
    RULES_SRC_DIR = content / "rules" / "rules"
    AGENTS_SRC_DIR = content / "rules" / "agents"
    SKILLS_SRC_DIR = content / "rules" / "skills"
    SYSTEM_SRC_DIR = content / "rules" / "system"
    TEMPLATES_DIR = content / "rules" / "templates"
    FRAMEWORK_CONFIG_SRC = SYSTEM_SRC_DIR / "framework.md"
    PROJECT_CONFIG_SRC = SYSTEM_SRC_DIR / "project.md"
    HOOKS_DIR = content / "rules" / "hooks"

    fw_dir = cfg.framework_dir

    # Backward compatibility: warn if old filenames still exist
    for old_name, new_path in [
        ("INTERNAL.md", FRAMEWORK_CONFIG_SRC),
        ("FRAMEWORK.md", FRAMEWORK_CONFIG_SRC),
        ("CUSTOM.md", PROJECT_CONFIG_SRC),
        ("PROJECT.md", PROJECT_CONFIG_SRC),
    ]:
        old = content / old_name
        if old.exists() and not new_path.exists():
            logger.warning(
                "Warning: %s/%s is deprecated. Migrate to %s",
                fw_dir,
                old_name,
                new_path.relative_to(root),
            )

    claude_dir = cfg.claude_dir
    gemini_dir = cfg.gemini_dir

    TOOL_CONFIGS = {
        "claude": ToolConfig(
            name="claude",
            rules_dir=root / claude_dir / "rules",
            agents_dir=root / claude_dir / "agents",
            skills_dir=root / claude_dir / "skills",
            config_file=root / claude_dir / "CLAUDE.md",
            system_file=None,
        ),
        "gemini": ToolConfig(
            name="gemini",
            rules_dir=root / gemini_dir / "rules",
            agents_dir=root / gemini_dir / "agents",
            skills_dir=root / gemini_dir / "skills",
            config_file=root / gemini_dir / "GEMINI.md",
            system_file=root / gemini_dir / "SYSTEM.md",
        ),
        "agents": ToolConfig(
            name="agents",
            rules_dir=None,
            agents_dir=None,
            skills_dir=None,
            config_file=root / "AGENTS.md",
            system_file=None,
        ),
        "agent": ToolConfig(
            name="agent",
            rules_dir=root / ".agent" / "rules",
            agents_dir=None,
            skills_dir=root / ".agent" / "skills",
            system_file=None,
        ),
    }
