"""Multi-resource manager for .vaultspec/ framework.

Manages rules, agents, and skills across tool-specific destinations
(Claude, Gemini, Antigravity) with format-aware frontmatter transformations
and tier-based model resolution.

Usage:
    python .vaultspec/lib/scripts/cli.py <resource> <command> [options]
    python .vaultspec/lib/scripts/cli.py sync-all [--prune] [--dry-run]
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from collections.abc import Callable

try:
    import yaml

    def _yaml_load(text: str) -> dict[str, Any]:
        return yaml.safe_load(text) or {}

    class _LiteralStr(str):
        """Marker type for strings that should use YAML literal block scalar."""

    def _literal_representer(dumper: yaml.Dumper, data: _LiteralStr) -> yaml.ScalarNode:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")

    yaml.add_representer(_LiteralStr, _literal_representer)

    def _yaml_dump(data: dict[str, Any]) -> str:
        prepared = {}
        for k, v in data.items():
            if isinstance(v, str) and "\n" in v:
                prepared[k] = _LiteralStr(v)
            else:
                prepared[k] = v
        return yaml.dump(
            prepared, default_flow_style=False, allow_unicode=True, sort_keys=False
        ).rstrip("\n")

except ImportError:

    def _yaml_load(text: str) -> dict[str, Any]:
        """Minimal 2-level YAML parser."""
        data: dict[str, Any] = {}
        current_key: str | None = None
        for line in text.splitlines():
            if not line.strip():
                continue
            # Indented line -> nested under current_key
            if line.startswith("  ") and current_key is not None:
                stripped = line.strip()
                if ":" in stripped:
                    k, v = stripped.split(":", 1)
                    if not isinstance(data[current_key], dict):
                        data[current_key] = {}
                    data[current_key][k.strip()] = v.strip()
                continue
            # Top-level key
            if ":" in line:
                k, v = line.split(":", 1)
                k = k.strip()
                v = v.strip()
                if v:
                    # Strip quotes
                    if (v.startswith('"') and v.endswith('"')) or (
                        v.startswith("'") and v.endswith("'")
                    ):
                        v = v[1:-1]
                    data[k] = v
                else:
                    data[k] = {}
                current_key = k
        return data

    def _yaml_dump(data: dict[str, Any]) -> str:
        """Minimal YAML serializer."""
        lines: list[str] = []
        for k, v in data.items():
            if isinstance(v, dict):
                lines.append(f"{k}:")
                for sk, sv in v.items():
                    lines.append(f"  {sk}: {sv}")
            elif isinstance(v, bool):
                lines.append(f"{k}: {'true' if v else 'false'}")
            elif isinstance(v, str) and (
                ":" in v or '"' in v or "'" in v or v != v.strip()
            ):
                lines.append(f'{k}: "{v}"')
            else:
                lines.append(f"{k}: {v}")
        return "\n".join(lines)


from _paths import LIB_SRC_DIR  # noqa: F401
from _paths import ROOT_DIR as _PATHS_ROOT_DIR  # shared path bootstrap
from logging_config import configure_logging

try:
    from protocol.providers.claude import ClaudeProvider
    from protocol.providers.gemini import GeminiProvider

    PROVIDERS: dict[str, Any] = {
        "claude": ClaudeProvider(),
        "gemini": GeminiProvider(),
    }
except ImportError:
    PROVIDERS = {}
    print(
        "Warning: agent_providers not found. Tier resolution unavailable.",
        file=sys.stderr,
    )


PROTECTED_SKILLS = {"fd", "rg", "sg", "sd"}

# AUTO-GENERATED header
CONFIG_HEADER = "<!-- AUTO-GENERATED by cli.py config sync. -->"


@dataclass
class ToolConfig:
    name: str
    rules_dir: Path | None
    agents_dir: Path | None
    skills_dir: Path | None
    config_file: Path | None = None
    system_file: Path | None = None


# Module-level globals initialised by init_paths()
ROOT_DIR: Path = Path()
RULES_SRC_DIR: Path = Path()
AGENTS_SRC_DIR: Path = Path()
SKILLS_SRC_DIR: Path = Path()
SYSTEM_SRC_DIR: Path = Path()
FRAMEWORK_CONFIG_SRC: Path = Path()
PROJECT_CONFIG_SRC: Path = Path()
CONSTITUTION_SRC: Path = Path()
HOOKS_DIR: Path = Path()
TOOL_CONFIGS: dict[str, ToolConfig] = {}


def init_paths(root: Path) -> None:
    """(Re-)initialise all path globals from *root*."""
    global ROOT_DIR, RULES_SRC_DIR, AGENTS_SRC_DIR
    global SKILLS_SRC_DIR, SYSTEM_SRC_DIR
    global FRAMEWORK_CONFIG_SRC, PROJECT_CONFIG_SRC
    global CONSTITUTION_SRC, HOOKS_DIR, TOOL_CONFIGS

    from core.config import get_config

    cfg = get_config()

    ROOT_DIR = root
    fw_dir = cfg.framework_dir
    RULES_SRC_DIR = root / fw_dir / "rules"
    AGENTS_SRC_DIR = root / fw_dir / "agents"
    SKILLS_SRC_DIR = root / fw_dir / "skills"
    SYSTEM_SRC_DIR = root / fw_dir / "system"
    FRAMEWORK_CONFIG_SRC = SYSTEM_SRC_DIR / "framework.md"
    PROJECT_CONFIG_SRC = SYSTEM_SRC_DIR / "project.md"
    CONSTITUTION_SRC = root / fw_dir / "constitution.md"
    HOOKS_DIR = root / fw_dir / "hooks"

    # Backward compatibility: warn if old filenames still exist
    for old_name, new_path in [
        ("INTERNAL.md", FRAMEWORK_CONFIG_SRC),
        ("FRAMEWORK.md", FRAMEWORK_CONFIG_SRC),
        ("CUSTOM.md", PROJECT_CONFIG_SRC),
        ("PROJECT.md", PROJECT_CONFIG_SRC),
    ]:
        old = root / fw_dir / old_name
        if old.exists() and not new_path.exists():
            print(
                f"Warning: {fw_dir}/{old_name} is deprecated."
                f" Migrate to {new_path.relative_to(root)}",
                file=sys.stderr,
            )

    claude_dir = cfg.claude_dir
    gemini_dir = cfg.gemini_dir

    TOOL_CONFIGS = {
        "claude": ToolConfig(
            name="claude",
            rules_dir=root / claude_dir / "rules",
            agents_dir=root / claude_dir / "agents",
            skills_dir=root / claude_dir / "skills",
            config_file=root / claude_dir / "CLAUDE.md",
            system_file=None,
        ),
        "gemini": ToolConfig(
            name="gemini",
            rules_dir=root / gemini_dir / "rules",
            agents_dir=root / gemini_dir / "agents",
            skills_dir=root / gemini_dir / "skills",
            config_file=root / gemini_dir / "GEMINI.md",
            system_file=root / gemini_dir / "SYSTEM.md",
        ),
        "agents": ToolConfig(
            name="agents",
            rules_dir=None,
            agents_dir=None,
            skills_dir=None,
            config_file=root / "AGENTS.md",
            system_file=None,
        ),
        "agent": ToolConfig(
            name="agent",
            rules_dir=root / ".agent" / "rules",
            agents_dir=None,
            skills_dir=root / ".agent" / "skills",
            system_file=None,
        ),
    }


def _get_version() -> str:
    """Read version from pyproject.toml."""
    toml_path = _PATHS_ROOT_DIR / "pyproject.toml"
    if toml_path.exists():
        for line in toml_path.read_text(encoding="utf-8").splitlines():
            if line.strip().startswith("version"):
                return line.split("=", 1)[1].strip().strip('"').strip("'")
    return "unknown"


# Default initialisation
init_paths(_PATHS_ROOT_DIR)


@dataclass
class SyncResult:
    added: int = 0
    updated: int = 0
    skipped: int = 0
    pruned: int = 0
    errors: list[str] = field(default_factory=list)


from vault.parser import parse_frontmatter  # noqa: E402


def build_file(frontmatter: dict[str, Any], body: str) -> str:
    """Assemble a file from frontmatter dict and body content."""
    fm_str = _yaml_dump(frontmatter)
    return f"---\n{fm_str}\n---\n\n{body}"


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def atomic_write(path: Path, content: str) -> None:
    """Write content to file atomically via tmp + rename."""
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(path)


def resolve_model(tool: str, tier: str) -> str | None:
    """Resolve a capability tier name to a model string."""
    if not PROVIDERS or tool not in PROVIDERS:
        return None
    try:
        from protocol.providers.base import CapabilityLevel

        level = CapabilityLevel[tier.upper()]
    except (ImportError, KeyError, AttributeError):
        return None
    return PROVIDERS[tool].get_best_model_for_capability(level)


def collect_rules() -> dict[str, tuple[Path, dict[str, Any], str]]:
    """Collect rules (builtin *.builtin.md + custom *.md) from rules/."""
    sources: dict[str, tuple[Path, dict[str, Any], str]] = {}

    if not RULES_SRC_DIR.exists():
        return sources
    for f in sorted(RULES_SRC_DIR.glob("*.md")):
        content = f.read_text(encoding="utf-8")
        meta, body = parse_frontmatter(content)
        sources[f.name] = (f, meta, body)

    return sources


def transform_rule(tool: str, name: str, _meta: dict[str, Any], body: str) -> str:
    """Transform a rule for a specific tool destination."""
    fm: dict[str, Any] = {}
    if tool != "agent":
        fm["name"] = Path(name).stem
    fm["trigger"] = "always_on"
    return build_file(fm, body)


def rules_list(_args: argparse.Namespace) -> None:
    print(f"{'Name':<40} {'Source':<15}")
    print("-" * 55)

    if RULES_SRC_DIR.exists():
        for f in sorted(RULES_SRC_DIR.glob("*.md")):
            source = "Built-in" if f.name.endswith(".builtin.md") else "Custom"
            print(f"{f.name:<40} {source:<15}")


def rules_add(args: argparse.Namespace) -> None:
    ensure_dir(RULES_SRC_DIR)

    file_name = args.name if args.name.endswith(".md") else f"{args.name}.md"
    file_path = RULES_SRC_DIR / file_name

    if file_path.exists() and not args.force:
        print(f"Error: Rule '{file_name}' exists. Use --force to overwrite.")
        return

    content = args.content

    if not content:
        if sys.stdin.isatty():
            from core.config import get_config

            editor = get_config().editor
            scaffold = f"---\nname: {args.name}\n---\n\n# Rule content\n"
            file_path.write_text(scaffold, encoding="utf-8")
            print(f"Opening editor ({editor}) for {file_path}...")
            try:
                subprocess.call([*editor.split(), str(file_path)])
                print(f"Rule saved to {file_path}")
            except Exception as e:
                print(f"Error opening editor: {e}")
            return
        else:
            content = sys.stdin.read()

    fm = {"name": args.name}
    full = build_file(fm, (content or "").lstrip())
    file_path.write_text(full, encoding="utf-8")
    print(f"Created custom rule: {file_path}")


def rules_sync(args: argparse.Namespace) -> None:
    sources = collect_rules()
    dry_run = getattr(args, "dry_run", False)
    prune = getattr(args, "prune", False)

    total = SyncResult()
    for tool_name, cfg in TOOL_CONFIGS.items():
        if cfg.rules_dir is None:
            continue
        result = sync_files(
            sources=sources,
            dest_dir=cfg.rules_dir,
            transform_fn=lambda _t, n, m, b, _tn=tool_name: transform_rule(
                _tn, n, m, b
            ),
            dest_path_fn=lambda dest_dir, name: dest_dir / name,
            prune=prune,
            dry_run=dry_run,
            label=f"rules -> {tool_name}",
        )
        total.added += result.added
        total.updated += result.updated
        total.pruned += result.pruned
        total.skipped += result.skipped
        total.errors.extend(result.errors)

    print_summary("Rules", total)


def collect_agents() -> dict[str, tuple[Path, dict[str, Any], str]]:
    """Collect agent definitions from .vaultspec/agents/."""
    sources: dict[str, tuple[Path, dict[str, Any], str]] = {}
    if not AGENTS_SRC_DIR.exists():
        return sources
    for f in sorted(AGENTS_SRC_DIR.glob("*.md")):
        content = f.read_text(encoding="utf-8")
        meta, body = parse_frontmatter(content)
        sources[f.name] = (f, meta, body)
    return sources


def transform_agent(
    tool: str,
    name: str,
    meta: dict[str, Any],
    body: str,
    *,
    resolve_fn: Callable[..., str | None] | None = None,
) -> str | None:
    """Transform an agent for a specific tool destination."""
    agent_name = Path(name).stem
    description = meta.get("description", "")
    tier = meta.get("tier", "")

    if not tier:
        print(f"  Warning: Agent '{agent_name}' missing tier.", file=sys.stderr)
        return None

    _resolve = resolve_fn or resolve_model
    model = _resolve(tool, tier)
    if model is None:
        msg = f"  Warning: No model for {tool}/{tier}. Skipping {agent_name}."
        print(msg, file=sys.stderr)
        return None

    fm = {
        "name": agent_name,
        "description": description,
        "kind": "local",
        "model": model,
    }
    return build_file(fm, body)


def agents_list(_args: argparse.Namespace) -> None:
    sources = collect_agents()
    if not sources:
        print("No agents found.")
        return

    print(f"{'Name':<25} {'Tier':<8} {'Claude':<25} {'Gemini':<25}")
    print("-" * 83)
    for name, meta_tuple in sources.items():
        _path, meta, _body = meta_tuple
        agent_name = Path(name).stem
        tier = meta.get("tier", "?")
        claude_model = resolve_model("claude", tier) or "?"
        gemini_model = resolve_model("gemini", tier) or "?"
        print(f"{agent_name:<25} {tier:<8} {claude_model:<25} {gemini_model:<25}")


def agents_add(args: argparse.Namespace) -> None:
    ensure_dir(AGENTS_SRC_DIR)

    file_name = args.name if args.name.endswith(".md") else f"{args.name}.md"
    file_path = AGENTS_SRC_DIR / file_name

    if file_path.exists() and not getattr(args, "force", False):
        print(f"Error: Agent '{file_name}' exists. Use --force to overwrite.")
        return

    description = getattr(args, "description", "") or ""
    tier = getattr(args, "tier", "MEDIUM") or "MEDIUM"

    default_body = f"# Persona: {args.name}\n\nDefine your agent persona here.\n"
    body = default_body
    if getattr(args, "template", None):
        from core.config import get_config

        cfg = get_config()
        tmpl_path = ROOT_DIR / cfg.framework_dir / "templates" / args.template
        if not tmpl_path.suffix:
            tmpl_path = tmpl_path.with_suffix(".md")
        if tmpl_path.exists():
            body = tmpl_path.read_text(encoding="utf-8")
        else:
            print(f"Warning: Template '{args.template}' not found at {tmpl_path}")

    fm = {"description": description, "tier": tier.upper()}
    scaffold = build_file(fm, body)

    if sys.stdin.isatty():
        file_path.write_text(scaffold, encoding="utf-8")
        from core.config import get_config

        editor = get_config().editor
        print(f"Opening editor ({editor}) for {file_path}...")
        try:
            subprocess.call([*editor.split(), str(file_path)])
            print(f"Agent saved to {file_path}")
        except Exception as e:
            print(f"Error opening editor: {e}")
    else:
        file_path.write_text(scaffold, encoding="utf-8")
        print(f"Created agent: {file_path}")


def agents_set_tier(args: argparse.Namespace) -> None:
    """Update the tier of an agent in its source file."""
    agent_name = args.name
    new_tier = args.tier.upper()

    if new_tier not in ("LOW", "MEDIUM", "HIGH"):
        print(f"Error: Invalid tier '{new_tier}'.")
        return

    file_name = agent_name if agent_name.endswith(".md") else f"{agent_name}.md"
    file_path = AGENTS_SRC_DIR / file_name

    if not file_path.exists():
        print(f"Error: Agent '{agent_name}' not found at {file_path}")
        return

    content = file_path.read_text(encoding="utf-8")
    meta, body = parse_frontmatter(content)
    old_tier = meta.get("tier", "?")
    meta["tier"] = new_tier

    atomic_write(file_path, build_file(meta, body))
    print(f"Updated {agent_name}: tier {old_tier} -> {new_tier}")

    # Show resolved models
    for tool_name in ["claude", "gemini"]:
        model = resolve_model(tool_name, new_tier)
        if model:
            print(f"  {tool_name}: {model}")

    print("Run 'agents sync' to propagate changes.")


def agents_sync(
    args: argparse.Namespace,
    *,
    resolve_fn: Callable[..., str | None] | None = None,
) -> None:
    sources = collect_agents()
    dry_run = getattr(args, "dry_run", False)
    prune = getattr(args, "prune", False)

    total = SyncResult()
    for tool_name, cfg in TOOL_CONFIGS.items():
        if cfg.agents_dir is None:
            continue
        result = sync_files(
            sources=sources,
            dest_dir=cfg.agents_dir,
            transform_fn=lambda _t, n, m, b, _tn=tool_name: transform_agent(
                _tn, n, m, b, resolve_fn=resolve_fn
            ),
            dest_path_fn=lambda dest_dir, name: dest_dir / name,
            prune=prune,
            dry_run=dry_run,
            label=f"agents -> {tool_name}",
        )
        total.added += result.added
        total.updated += result.updated
        total.pruned += result.pruned
        total.skipped += result.skipped
        total.errors.extend(result.errors)

    print_summary("Agents", total)


def collect_skills() -> dict[str, tuple[Path, dict[str, Any], str]]:
    """Collect vaultspec-* skill definitions from .vaultspec/skills/."""
    sources: dict[str, tuple[Path, dict[str, Any], str]] = {}
    if not SKILLS_SRC_DIR.exists():
        return sources
    for f in sorted(SKILLS_SRC_DIR.glob("vaultspec-*.md")):
        content = f.read_text(encoding="utf-8")
        meta, body = parse_frontmatter(content)
        sources[f.stem] = (f, meta, body)
    return sources


def transform_skill(_tool: str, name: str, meta: dict[str, Any], body: str) -> str:
    """Transform a skill for a specific tool destination."""
    description = meta.get("description", "")
    fm = {"name": name, "description": description}
    return build_file(fm, body)


def skill_dest_path(dest_dir: Path, name: str) -> Path:
    """Skill destination is a directory with SKILL.md inside."""
    return dest_dir / name / "SKILL.md"


def skills_list(_args: argparse.Namespace) -> None:
    sources = collect_skills()
    if not sources:
        print("No managed skills found.")
        return

    print(f"{'Name':<30} {'Description':<60}")
    print("-" * 90)
    for name, meta_tuple in sources.items():
        _path, meta, _body = meta_tuple
        desc = meta.get("description", "")
        if len(desc) > 57:
            desc = desc[:57] + "..."
        print(f"{name:<30} {desc:<60}")


def skills_add(args: argparse.Namespace) -> None:
    ensure_dir(SKILLS_SRC_DIR)

    skill_name = args.name
    if not skill_name.startswith("vaultspec-"):
        skill_name = f"vaultspec-{skill_name}"
    file_name = f"{skill_name}.md"
    file_path = SKILLS_SRC_DIR / file_name

    if file_path.exists() and not getattr(args, "force", False):
        print(f"Error: Skill '{file_name}' exists. Use --force to overwrite.")
        return

    description = getattr(args, "description", "") or ""
    default_body = f"# {skill_name}\n\nDefine your skill instructions here.\n"
    body = default_body
    if getattr(args, "template", None):
        from core.config import get_config as _get_cfg

        cfg = _get_cfg()
        tmpl_path = ROOT_DIR / cfg.framework_dir / "templates" / args.template
        if not tmpl_path.suffix:
            tmpl_path = tmpl_path.with_suffix(".md")
        if tmpl_path.exists():
            body = tmpl_path.read_text(encoding="utf-8")
        else:
            print(f"Warning: Template '{args.template}' not found at {tmpl_path}")

    fm = {"description": description}
    scaffold = build_file(fm, body)

    if sys.stdin.isatty():
        file_path.write_text(scaffold, encoding="utf-8")
        from core.config import get_config

        editor = get_config().editor
        print(f"Opening editor ({editor}) for {file_path}...")
        try:
            subprocess.call([*editor.split(), str(file_path)])
            print(f"Skill saved to {file_path}")
        except Exception as e:
            print(f"Error opening editor: {e}")
    else:
        file_path.write_text(scaffold, encoding="utf-8")
        print(f"Created skill: {file_path}")


def resource_show(args: argparse.Namespace, src_dir: Path, label: str) -> None:
    """Display a single resource file."""
    name = args.name
    file_name = name if name.endswith(".md") else f"{name}.md"
    file_path = src_dir / file_name
    if not file_path.exists():
        print(f"Error: {label} '{name}' not found at {file_path}")
        return
    content = file_path.read_text(encoding="utf-8")
    meta, body = parse_frontmatter(content)
    if meta:
        print("--- Metadata ---")
        for k, v in meta.items():
            print(f"  {k}: {v}")
        print("---")
    print(body)


def resource_edit(args: argparse.Namespace, src_dir: Path, label: str) -> None:
    """Open a resource file in the user's editor."""
    name = args.name
    file_name = name if name.endswith(".md") else f"{name}.md"
    file_path = src_dir / file_name
    if not file_path.exists():
        print(f"Error: {label} '{name}' not found at {file_path}")
        return
    from core.config import get_config

    editor = (
        os.environ.get("VAULTSPEC_EDITOR")
        or os.environ.get("VISUAL")
        or os.environ.get("EDITOR")
        or get_config().editor
    )
    try:
        subprocess.call([*editor.split(), str(file_path)])
    except Exception as e:
        print(f"Error opening editor: {e}")


def resource_remove(args: argparse.Namespace, src_dir: Path, label: str) -> None:
    """Delete a resource file and its synced copies."""
    name = args.name
    file_name = name if name.endswith(".md") else f"{name}.md"
    file_path = src_dir / file_name
    if not file_path.exists():
        print(f"Error: {label} '{name}' not found at {file_path}")
        return

    if not getattr(args, "force", False):
        confirm = input(f"Remove {label} '{name}'? [y/N] ").strip().lower()
        if confirm != "y":
            print("Cancelled.")
            return

    file_path.unlink()
    print(f"Removed {file_path}")

    # Prune synced copies
    removed = 0
    skill_name = name if not name.endswith(".md") else name[:-3]
    for _tool_name, cfg in TOOL_CONFIGS.items():
        dest_dir = None
        if label == "Rule" and cfg.rules_dir:
            dest_dir = cfg.rules_dir
        elif label == "Agent" and cfg.agents_dir:
            dest_dir = cfg.agents_dir
        elif label == "Skill" and cfg.skills_dir:
            dest_dir = cfg.skills_dir
        if dest_dir:
            if label == "Skill":
                synced = skill_dest_path(dest_dir, skill_name)
            else:
                synced = dest_dir / file_name
            if synced.exists():
                synced.unlink()
                # Remove parent dir if empty (skill dirs)
                if (
                    label == "Skill"
                    and synced.parent.exists()
                    and not any(synced.parent.iterdir())
                ):
                    synced.parent.rmdir()
                removed += 1
    if removed:
        print(f"  Pruned {removed} synced copies.")


def resource_rename(args: argparse.Namespace, src_dir: Path, label: str) -> None:
    """Rename a resource file and update synced copies."""
    old_name = args.old_name
    new_name = args.new_name
    old_file = old_name if old_name.endswith(".md") else f"{old_name}.md"
    new_file = new_name if new_name.endswith(".md") else f"{new_name}.md"
    old_path = src_dir / old_file
    new_path = src_dir / new_file

    if not old_path.exists():
        print(f"Error: {label} '{old_name}' not found at {old_path}")
        return
    if new_path.exists():
        print(f"Error: {label} '{new_name}' already exists at {new_path}")
        return

    old_path.rename(new_path)
    print(f"Renamed {old_file} -> {new_file}")

    # Update synced copies
    updated = 0
    old_skill = old_name if not old_name.endswith(".md") else old_name[:-3]
    new_skill = new_name if not new_name.endswith(".md") else new_name[:-3]
    for _tool_name, cfg in TOOL_CONFIGS.items():
        dest_dir = None
        if label == "Rule" and cfg.rules_dir:
            dest_dir = cfg.rules_dir
        elif label == "Agent" and cfg.agents_dir:
            dest_dir = cfg.agents_dir
        elif label == "Skill" and cfg.skills_dir:
            dest_dir = cfg.skills_dir
        if dest_dir:
            if label == "Skill":
                old_synced = skill_dest_path(dest_dir, old_skill)
                if old_synced.exists():
                    new_parent = dest_dir / new_skill
                    ensure_dir(new_parent)
                    old_synced.rename(new_parent / "SKILL.md")
                    # Remove old parent dir if empty
                    if old_synced.parent.exists() and not any(
                        old_synced.parent.iterdir()
                    ):
                        old_synced.parent.rmdir()
                    updated += 1
            else:
                old_synced = dest_dir / old_file
                if old_synced.exists():
                    old_synced.rename(dest_dir / new_file)
                    updated += 1
    if updated:
        print(f"  Updated {updated} synced copies.")
    print("Run 'sync-all' to ensure all destinations are current.")


def skills_sync(args: argparse.Namespace) -> None:
    sources = collect_skills()
    dry_run = getattr(args, "dry_run", False)
    prune = getattr(args, "prune", False)

    total = SyncResult()
    for tool_name, cfg in TOOL_CONFIGS.items():
        if cfg.skills_dir is None:
            continue
        result = sync_skills(
            sources=sources,
            skills_dir=cfg.skills_dir,
            transform_fn=lambda _t, n, m, b, _tn=tool_name: transform_skill(
                _tn, n, m, b
            ),
            prune=prune,
            dry_run=dry_run,
            label=f"skills -> {tool_name}",
        )
        total.added += result.added
        total.updated += result.updated
        total.pruned += result.pruned
        total.skipped += result.skipped
        total.errors.extend(result.errors)

    print_summary("Skills", total)


def sync_files(
    sources: dict[str, tuple[Path, dict[str, Any], str]],
    dest_dir: Path,
    transform_fn,
    dest_path_fn,
    prune: bool,
    dry_run: bool,
    label: str,
) -> SyncResult:
    """Sync source files to a destination directory."""
    result = SyncResult()
    ensure_dir(dest_dir)

    print(f"  Syncing {label}...")

    for name, meta_tuple in sources.items():
        _src_path, meta, body = meta_tuple
        dest_path = dest_path_fn(dest_dir, name)
        try:
            content = transform_fn(None, name, meta, body)
            if content is None:
                result.skipped += 1
                continue

            action = "[UPDATE]" if dest_path.exists() else "[ADD]"

            if dry_run:
                rel = dest_path.relative_to(ROOT_DIR)
                print(f"    {action} {rel}")
            else:
                ensure_dir(dest_path.parent)
                atomic_write(dest_path, content)

            if action == "[ADD]":
                result.added += 1
            else:
                result.updated += 1

        except Exception as e:
            result.errors.append(f"{name}: {e}")
            print(f"    [ERROR] {name}: {e}", file=sys.stderr)

    # Prune
    if prune:
        source_names = set(sources.keys())
        if dest_dir.exists():
            for existing in dest_dir.glob("*.md"):
                if existing.name not in source_names:
                    rel = existing.relative_to(ROOT_DIR)
                    if dry_run:
                        print(f"    [PRUNE] {rel}")
                    else:
                        existing.unlink()
                    result.pruned += 1

    return result


def sync_skills(
    sources: dict[str, tuple[Path, dict[str, Any], str]],
    skills_dir: Path,
    transform_fn,
    prune: bool,
    dry_run: bool,
    label: str,
) -> SyncResult:
    """Sync skill files to a destination skills directory."""
    result = SyncResult()
    ensure_dir(skills_dir)

    print(f"  Syncing {label}...")

    for name, meta_tuple in sources.items():
        _src_path, meta, body = meta_tuple
        dest_path = skill_dest_path(skills_dir, name)
        try:
            content = transform_fn(None, name, meta, body)
            if content is None:
                result.skipped += 1
                continue

            action = "[UPDATE]" if dest_path.exists() else "[ADD]"

            if dry_run:
                rel = dest_path.relative_to(ROOT_DIR)
                print(f"    {action} {rel}")
            else:
                ensure_dir(dest_path.parent)
                atomic_write(dest_path, content)

            if action == "[ADD]":
                result.added += 1
            else:
                result.updated += 1

        except Exception as e:
            result.errors.append(f"{name}: {e}")
            print(f"    [ERROR] {name}: {e}", file=sys.stderr)

    # Prune: only prune vaultspec-* prefixed skill dirs
    if prune:
        source_names = set(sources.keys())
        if skills_dir.exists():
            for skill_subdir in skills_dir.iterdir():
                if not skill_subdir.is_dir():
                    continue
                if skill_subdir.name in PROTECTED_SKILLS:
                    continue
                if not skill_subdir.name.startswith("vaultspec-"):
                    continue
                if skill_subdir.name not in source_names:
                    skill_md = skill_subdir / "SKILL.md"
                    if skill_md.exists():
                        rel = skill_md.relative_to(ROOT_DIR)
                        if dry_run:
                            print(f"    [PRUNE] {rel}")
                        else:
                            skill_md.unlink()
                            if not any(skill_subdir.iterdir()):
                                skill_subdir.rmdir()
                        result.pruned += 1

    return result


def _read_constitution() -> str | None:
    """Read constitution body content if it exists."""
    if not CONSTITUTION_SRC.exists():
        return None
    content = CONSTITUTION_SRC.read_text(encoding="utf-8")
    _meta, body = parse_frontmatter(content)
    return body.strip() if body else None


def _collect_rule_refs(cfg: ToolConfig) -> list[str]:
    """Collect rule file references."""
    if cfg.rules_dir is None or cfg.config_file is None:
        if cfg.name == "agents" and cfg.config_file:
            config_dir = cfg.config_file.parent
            refs = []
            sources = collect_rules()
            for name in sorted(sources.keys()):
                src_path, _meta, _body = sources[name]
                try:
                    rel = src_path.relative_to(config_dir)
                    refs.append(str(rel).replace("\\", "/"))
                except ValueError:
                    ref = src_path.relative_to(ROOT_DIR)
                    refs.append(str(ref).replace("\\", "/"))
            return refs
        return []
    if not cfg.rules_dir.exists():
        return []

    config_dir = cfg.config_file.parent
    refs = []
    for rule_file in sorted(cfg.rules_dir.glob("*.md")):
        try:
            rel = rule_file.relative_to(config_dir)
            refs.append(str(rel).replace("\\", "/"))
        except ValueError:
            ref = rule_file.relative_to(ROOT_DIR)
            refs.append(str(ref).replace("\\", "/"))
    return refs


def _generate_agents_md(cfg: ToolConfig) -> str | None:
    """Generate AGENTS.md in the agents.md standard format.

    Produces YAML frontmatter with ``description`` and ``alwaysApply``
    fields, followed by the framework content as plain Markdown sections
    (XML tags stripped), project content, and rule references.
    """
    if not FRAMEWORK_CONFIG_SRC.exists():
        return None

    _meta, internal_body = parse_frontmatter(
        FRAMEWORK_CONFIG_SRC.read_text(encoding="utf-8")
    )
    internal_body = internal_body.strip()

    # Strip XML tags (e.g. <identity>, </identity>) — convert to Markdown headings
    def _xml_to_heading(text: str) -> str:
        """Convert <tag> ... </tag> blocks to ## Tag sections."""
        # Replace opening tags with headings
        text = re.sub(
            r"<(\w+)>\s*",
            lambda m: f"## {m.group(1).replace('_', ' ').title()}\n\n",
            text,
        )
        # Remove closing tags
        text = re.sub(r"</\w+>\s*", "\n", text)
        return text.strip()

    body_content = _xml_to_heading(internal_body)

    custom_body = ""
    if PROJECT_CONFIG_SRC.exists():
        _meta, custom_body = parse_frontmatter(
            PROJECT_CONFIG_SRC.read_text(encoding="utf-8")
        )
        custom_body = custom_body.strip()

    # Build standard agents.md frontmatter
    fm = {
        "description": "vaultspec — a governed development framework for AI agents",
        "alwaysApply": True,
    }

    # Assemble body
    body_parts = [body_content]

    if custom_body:
        body_parts.append("")
        body_parts.append(custom_body)

    # Add constitution
    constitution_body = _read_constitution()
    if constitution_body:
        body_parts.append("")
        body_parts.append("## Constitution")
        body_parts.append("")
        body_parts.append("The following principles are immutable:")
        body_parts.append("")
        body_parts.append(constitution_body)

    # Add rules
    refs = _collect_rule_refs(cfg)
    if refs:
        body_parts.append("")
        body_parts.append("## Rules")
        body_parts.append("")
        body_parts.append("You MUST respect these rules at all times:")
        body_parts.append("")
        for ref in refs:
            body_parts.append(f"@{ref}")

    body = "\n".join(body_parts)
    return f"{CONFIG_HEADER}\n{build_file(fm, body)}"


def _generate_config(cfg: ToolConfig) -> str | None:
    """Generate config file content."""
    if not FRAMEWORK_CONFIG_SRC.exists():
        return None

    _meta, internal_body = parse_frontmatter(
        FRAMEWORK_CONFIG_SRC.read_text(encoding="utf-8")
    )
    internal_body = internal_body.strip()
    custom_body = ""
    if PROJECT_CONFIG_SRC.exists():
        _meta, custom_body = parse_frontmatter(
            PROJECT_CONFIG_SRC.read_text(encoding="utf-8")
        )
        custom_body = custom_body.strip()

    fm = {"system_framework": internal_body}

    # Body starts with custom content
    body_parts = []
    if custom_body:
        body_parts.append(custom_body)

    # Add constitution
    constitution_body = _read_constitution()
    if constitution_body:
        if body_parts:
            body_parts.append("")
        body_parts.append("## Constitution")
        body_parts.append("")
        body_parts.append("The following principles are immutable:")
        body_parts.append("")
        body_parts.append(constitution_body)

    # Add rules
    refs = _collect_rule_refs(cfg)
    if refs:
        if body_parts:
            body_parts.append("")
        body_parts.append("## Rules")
        body_parts.append("")
        body_parts.append("You MUST respect these rules at all times:")
        body_parts.append("")
        for ref in refs:
            body_parts.append(f"@{ref}")

    body = "\n".join(body_parts)
    return f"{CONFIG_HEADER}\n{build_file(fm, body)}"


def _is_cli_managed(path: Path) -> bool:
    """Check if a config file was generated by this CLI."""
    if not path.exists():
        return False
    try:
        content = path.read_text(encoding="utf-8")
        return content.startswith(CONFIG_HEADER)
    except Exception:
        return False


def constitution_show(_args: argparse.Namespace) -> None:
    """Display current constitution content."""
    if not CONSTITUTION_SRC.exists():
        rel = CONSTITUTION_SRC.relative_to(ROOT_DIR)
        print(f"No constitution found at {rel}")
        print("Run 'constitution init' to create from template.")
        return

    print(f"Constitution: {CONSTITUTION_SRC.relative_to(ROOT_DIR)}")
    print("-" * 60)
    content = CONSTITUTION_SRC.read_text(encoding="utf-8")
    meta, body = parse_frontmatter(content)
    if meta:
        print("--- Metadata ---")
        for k, v in meta.items():
            print(f"  {k}: {v}")
        print("---")
    print(body.strip())
    print("-" * 60)


def constitution_init(args: argparse.Namespace) -> None:
    """Create constitution.md from template."""
    from core.config import get_config

    cfg = get_config()
    template_path = ROOT_DIR / cfg.framework_dir / "templates" / "constitution.md"

    if not template_path.exists():
        print(f"Error: Template not found at {template_path.relative_to(ROOT_DIR)}")
        return

    if CONSTITUTION_SRC.exists() and not getattr(args, "force", False):
        rel = CONSTITUTION_SRC.relative_to(ROOT_DIR)
        print(f"Error: Constitution already exists at {rel}. Use --force to overwrite.")
        return

    template_content = template_path.read_text(encoding="utf-8")
    ensure_dir(CONSTITUTION_SRC.parent)
    atomic_write(CONSTITUTION_SRC, template_content)
    rel = CONSTITUTION_SRC.relative_to(ROOT_DIR)
    print(f"Created constitution at {rel}")
    print("Run 'config sync' to propagate to tool configurations.")


def config_show(_args: argparse.Namespace) -> None:
    """Display internal/custom content and references."""
    if not FRAMEWORK_CONFIG_SRC.exists():
        rel = FRAMEWORK_CONFIG_SRC.relative_to(ROOT_DIR)
        print(f"No framework config found at {rel}")
        return

    print(f"Framework: {FRAMEWORK_CONFIG_SRC.relative_to(ROOT_DIR)}")
    print("-" * 60)
    _meta, fw_body = parse_frontmatter(FRAMEWORK_CONFIG_SRC.read_text(encoding="utf-8"))
    print(fw_body.strip())
    print("-" * 60)

    if PROJECT_CONFIG_SRC.exists():
        print(f"Project: {PROJECT_CONFIG_SRC.relative_to(ROOT_DIR)}")
        print("-" * 60)
        _meta, proj_body = parse_frontmatter(
            PROJECT_CONFIG_SRC.read_text(encoding="utf-8")
        )
        print(proj_body.strip())
        print("-" * 60)

    print("Generated references per tool:")
    for tool_name, cfg in TOOL_CONFIGS.items():
        if cfg.config_file is None:
            continue
        refs = _collect_rule_refs(cfg)
        dest_rel = cfg.config_file.relative_to(ROOT_DIR)
        managed = "CLI-managed" if _is_cli_managed(cfg.config_file) else "custom"
        print(f"\n  {tool_name} ({dest_rel}) [{managed}]:")
        if refs:
            for ref in refs:
                print(f"    @{ref}")
        else:
            print("    (no rules synced yet)")


def config_sync(args: argparse.Namespace) -> None:
    """Sync internal and custom configs to tool configs."""
    dry_run = getattr(args, "dry_run", False)
    force = getattr(args, "force", False)

    if not FRAMEWORK_CONFIG_SRC.exists():
        rel = FRAMEWORK_CONFIG_SRC.relative_to(ROOT_DIR)
        print(f"  Error: No framework config found at {rel}")
        return

    result = SyncResult()

    for _tool_name, cfg in TOOL_CONFIGS.items():
        if cfg.config_file is None:
            continue

        # Use agents.md standard format for AGENTS.md
        if cfg.name == "agents":
            content = _generate_agents_md(cfg)
        else:
            content = _generate_config(cfg)
        if content is None:
            result.skipped += 1
            continue

        rel = cfg.config_file.relative_to(ROOT_DIR)

        # Safety guard
        if (
            cfg.config_file.exists()
            and not _is_cli_managed(cfg.config_file)
            and not force
        ):
            print(f"    [SKIP] {rel} - file exists with custom content.")
            proj_rel = PROJECT_CONFIG_SRC.relative_to(ROOT_DIR)
            msg = f"           Migrate to {proj_rel}, then --force."
            print(msg)
            result.skipped += 1
            continue

        action = "[UPDATE]" if cfg.config_file.exists() else "[ADD]"

        if dry_run:
            print(f"    {action} {rel}")
        else:
            ensure_dir(cfg.config_file.parent)
            atomic_write(cfg.config_file, content)

        if action == "[ADD]":
            result.added += 1
        else:
            result.updated += 1

    print_summary("Config", result)


def collect_system_parts() -> dict[str, tuple[Path, dict[str, Any], str]]:
    """Collect system prompt parts from .vaultspec/system/."""
    sources: dict[str, tuple[Path, dict[str, Any], str]] = {}
    if not SYSTEM_SRC_DIR.exists():
        return sources
    for f in sorted(SYSTEM_SRC_DIR.glob("*.md")):
        content = f.read_text(encoding="utf-8")
        meta, body = parse_frontmatter(content)
        sources[f.stem] = (f, meta, body)
    return sources


def _collect_agent_listing() -> str:
    """Build a markdown section listing available agents."""
    agents = collect_agents()
    if not agents:
        return ""
    lines = [
        "## Available Sub-Agents",
        "",
        "Sub-agents are specialized expert agents available in `.vaultspec/agents/`.",
        "Dispatch using the `vaultspec-subagent` skill.",
        "",
    ]
    for name, meta_tuple in agents.items():
        _path, meta, _body = meta_tuple
        agent_name = Path(name).stem
        tier = meta.get("tier", "?")
        description = meta.get("description", "")
        lines.append(f"- **{agent_name}** ({tier}): {description}")
    return "\n".join(lines)


def _collect_skill_listing() -> str:
    """Build a markdown section listing available skills."""
    skills = collect_skills()
    if not skills:
        return ""
    lines = [
        "## Available Skills",
        "",
    ]
    for name, meta_tuple in skills.items():
        _path, meta, _body = meta_tuple
        description = meta.get("description", "")
        lines.append(f"- **{name}**: {description}")
    return "\n".join(lines)


def _generate_system_prompt(cfg: ToolConfig) -> str | None:
    """Assemble system prompt for a tool from .vaultspec/system/ parts."""
    if cfg.system_file is None:
        return None

    parts = collect_system_parts()
    if not parts:
        return None

    assembled: list[str] = [CONFIG_HEADER]

    # 1. base.md body first
    if "base" in parts:
        _path, _meta, body = parts["base"]
        assembled.append(body)

    # 2. Tool-specific parts (where meta "tool" matches cfg.name)
    for name, (_path, meta, body) in sorted(parts.items()):
        if name == "base":
            continue
        tool_filter = meta.get("tool")
        if tool_filter is not None and tool_filter == cfg.name:
            assembled.append(body)

    # 3. Auto-generated agent listing
    agent_listing = _collect_agent_listing()
    if agent_listing:
        assembled.append(agent_listing)

    # 4. Auto-generated skill listing
    skill_listing = _collect_skill_listing()
    if skill_listing:
        assembled.append(skill_listing)

    # 5. Remaining shared parts (no "tool" key, not "base", not config-only)
    #    Sorted by order frontmatter (default 50), then by name.
    shared = [
        (name, _path, meta, body)
        for name, (_path, meta, body) in parts.items()
        if name != "base"
        and meta.get("tool") is None
        and meta.get("pipeline") != "config"
    ]
    shared.sort(key=lambda t: (t[2].get("order", 50), t[0]))
    for _name, _path, _meta, body in shared:
        assembled.append(body)

    return "\n\n".join(assembled)


def _generate_system_rules(cfg: ToolConfig) -> str | None:
    """Assemble shared behavioral content as a rule file.

    For tools without system_file."""
    if cfg.rules_dir is None:
        return None

    parts = collect_system_parts()
    if not parts:
        return None

    assembled: list[str] = []

    # 1. base.md body first
    if "base" in parts:
        _path, _meta, body = parts["base"]
        assembled.append(body)

    # 2. Shared parts only (no "tool" key, not "base", not config-only)
    #    Sorted by order frontmatter (default 50), then by name.
    shared = [
        (name, _path, meta, body)
        for name, (_path, meta, body) in parts.items()
        if name != "base"
        and meta.get("tool") is None
        and meta.get("pipeline") != "config"
    ]
    shared.sort(key=lambda t: (t[2].get("order", 50), t[0]))
    for _name, _path, _meta, body in shared:
        assembled.append(body)

    if not assembled:
        return None

    content = "\n\n".join(assembled)
    fm = {"name": "vaultspec-system", "trigger": "always_on"}
    return f"{CONFIG_HEADER}\n{build_file(fm, content)}"


def system_show(_args: argparse.Namespace) -> None:
    """Display system parts table and generation targets."""
    parts = collect_system_parts()
    if not parts:
        print("No system parts found in .vaultspec/system/")
        return

    print(f"{'Name':<25} {'Tool Filter':<15} {'Lines':<8}")
    print("-" * 48)
    for name, (_path, meta, body) in sorted(parts.items()):
        tool_filter = meta.get("tool", "-")
        line_count = len(body.strip().splitlines()) if body.strip() else 0
        print(f"{name:<25} {tool_filter:<15} {line_count:<8}")

    print("\nGeneration targets:")
    for tool_name, cfg in TOOL_CONFIGS.items():
        if cfg.system_file is None:
            continue
        rel = cfg.system_file.relative_to(ROOT_DIR)
        managed = "CLI-managed" if _is_cli_managed(cfg.system_file) else "custom"
        print(f"  {tool_name}: {rel} [{managed}]")


def system_sync(args: argparse.Namespace) -> None:
    """Sync assembled system prompts and behavioral rules to tool destinations."""
    dry_run = getattr(args, "dry_run", False)
    force = getattr(args, "force", False)

    result = SyncResult()

    for _tool_name, cfg in TOOL_CONFIGS.items():
        # Path A: Tool has a system_file -> generate assembled SYSTEM.md
        if cfg.system_file is not None:
            content = _generate_system_prompt(cfg)
            if content is None:
                result.skipped += 1
                continue

            rel = cfg.system_file.relative_to(ROOT_DIR)

            # Safety guard
            if (
                cfg.system_file.exists()
                and not _is_cli_managed(cfg.system_file)
                and not force
            ):
                print(f"    [SKIP] {rel} - file exists with custom content.")
                print("           Use --force to overwrite.")
                result.skipped += 1
                continue

            action = "[UPDATE]" if cfg.system_file.exists() else "[ADD]"

            if dry_run:
                print(f"    {action} {rel}")
            else:
                ensure_dir(cfg.system_file.parent)
                atomic_write(cfg.system_file, content)

            if action == "[ADD]":
                result.added += 1
            else:
                result.updated += 1

        # Path B: Tool has rules_dir but no system_file -> generate behavioral rule
        elif cfg.rules_dir is not None:
            content = _generate_system_rules(cfg)
            if content is None:
                continue

            rule_path = cfg.rules_dir / "vaultspec-system.builtin.md"
            rel = rule_path.relative_to(ROOT_DIR)
            action = "[UPDATE]" if rule_path.exists() else "[ADD]"

            if dry_run:
                print(f"    {action} {rel}")
            else:
                ensure_dir(cfg.rules_dir)
                atomic_write(rule_path, content)

            if action == "[ADD]":
                result.added += 1
            else:
                result.updated += 1

    print_summary("System", result)


def print_summary(resource: str, result: SyncResult) -> None:
    parts = []
    if result.added:
        parts.append(f"{result.added} added")
    if result.updated:
        parts.append(f"{result.updated} updated")
    if result.pruned:
        parts.append(f"{result.pruned} pruned")
    if result.skipped:
        parts.append(f"{result.skipped} skipped")
    if result.errors:
        parts.append(f"{len(result.errors)} errors")
    summary = ", ".join(parts) if parts else "no changes"
    print(f"  {resource}: {summary}")


VALID_CATEGORIES = {"all", "unit", "api", "search", "index", "quality"}

MODULE_PATHS = {
    "cli": [".vaultspec/lib/tests/cli"],
    "rag": [".vaultspec/lib/tests/rag", ".vaultspec/lib/src/rag/tests"],
    "vault": [".vaultspec/lib/src/vault/tests"],
    "protocol": [".vaultspec/lib/src/protocol/tests"],
    "orchestration": [".vaultspec/lib/src/orchestration/tests"],
    "subagent": [
        ".vaultspec/lib/tests/subagent",
        ".vaultspec/lib/src/subagent_server/tests",
    ],
}


def test_run(args: argparse.Namespace) -> None:
    category = getattr(args, "category", "all") or "all"
    module = getattr(args, "module", None)
    extra = getattr(args, "extra_args", []) or []

    cmd = [sys.executable, "-m", "pytest"]

    if category != "all":
        cmd.extend(["-m", category])

    if module:
        if module not in MODULE_PATHS:
            valid = ", ".join(sorted(MODULE_PATHS))
            print(f"Error: Unknown module '{module}'. Valid: {valid}")
            return
        for p in MODULE_PATHS[module]:
            cmd.append(str(ROOT_DIR / p))
    else:
        cmd.append(str(ROOT_DIR / ".vaultspec" / "lib" / "tests"))
        cmd.append(str(ROOT_DIR / ".vaultspec" / "lib" / "src"))

    cmd.extend(extra)

    print(f"Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=str(ROOT_DIR))
    sys.exit(result.returncode)


def doctor_run(_args: argparse.Namespace) -> None:
    """Check prerequisites and system health."""
    import importlib

    issues = []

    # Python version
    ver = sys.version_info
    print(f"Python: {ver.major}.{ver.minor}.{ver.micro}", end="")
    if ver >= (3, 13):
        print(" [OK]")
    else:
        print(" [WARN] Python 3.13+ recommended")
        issues.append("Python 3.13+ recommended")

    # CUDA/GPU
    try:
        import torch

        if torch.cuda.is_available():
            props = torch.cuda.get_device_properties(0)
            mem = getattr(props, "total_memory", None) or getattr(props, "total_mem", 0)
            mem_gb = mem / (1024**3)
            print(f"CUDA: {torch.version.cuda} [OK]")
            print(f"GPU: {props.name} ({mem_gb:.1f} GB) [OK]")
        else:
            print("CUDA: Not available [FAIL]")
            issues.append("CUDA not available - GPU required")
    except ImportError:
        print("PyTorch: Not installed [FAIL]")
        issues.append("PyTorch not installed")

    # Optional deps
    for pkg, group in [
        ("lancedb", "rag"),
        ("sentence_transformers", "rag"),
        ("pytest", "dev"),
        ("ruff", "dev"),
    ]:
        try:
            importlib.import_module(pkg)
            print(f"{pkg}: installed [OK]")
        except ImportError:
            print(
                f"{pkg}: not installed [WARN]"
                f" (install with pip install -e '.[{group}]')"
            )
            issues.append(f"{pkg} not installed")

    # .lance directory
    lance_dir = ROOT_DIR / ".vault" / ".lance"
    if lance_dir.exists():
        size = sum(f.stat().st_size for f in lance_dir.rglob("*") if f.is_file())
        size_mb = size / (1024 * 1024)
        print(f".lance index: {size_mb:.1f} MB [OK]")
    else:
        print(".lance index: not built [INFO] (run 'docs.py index' to build)")

    # Summary
    if issues:
        print(f"\n{len(issues)} issue(s) found:")
        for issue in issues:
            print(f"  - {issue}")
    else:
        print("\nAll checks passed.")


def init_run(args: argparse.Namespace) -> None:
    """Initialize vaultspec in a project."""
    from core.config import get_config

    cfg = get_config()
    fw_dir = ROOT_DIR / cfg.framework_dir
    vault_dir = ROOT_DIR / ".vault"

    if fw_dir.exists() and not getattr(args, "force", False):
        print(f"Error: {fw_dir} already exists. Use --force to overwrite.")
        return

    # Create .vaultspec/ structure
    created = []
    for subdir in ["agents", "rules", "skills", "templates", "system"]:
        d = fw_dir / subdir
        ensure_dir(d)
        created.append(str(d.relative_to(ROOT_DIR)))

    # Create .vault/ structure
    for subdir in ["adr", "audit", "exec", "plan", "reference", "research"]:
        d = vault_dir / subdir
        ensure_dir(d)
        created.append(str(d.relative_to(ROOT_DIR)))

    # Create minimal stubs if they don't exist
    # Stubs go in system/ (canonical location per
    # FRAMEWORK_CONFIG_SRC / PROJECT_CONFIG_SRC)
    sys_dir = fw_dir / "system"
    fw_md = sys_dir / "framework.md"
    if not fw_md.exists():
        fw_md.write_text(
            "# Framework Configuration\n\nAdd framework bootstrap content here.\n",
            encoding="utf-8",
        )
        created.append(str(fw_md.relative_to(ROOT_DIR)))

    proj_md = sys_dir / "project.md"
    if not proj_md.exists():
        proj_md.write_text(
            "# Project Configuration\n\nAdd project-specific content here.\n",
            encoding="utf-8",
        )
        created.append(str(proj_md.relative_to(ROOT_DIR)))

    print("Initialized vaultspec structure:")
    for path in created:
        print(f"  {path}")
    print(f"\nCreated {len(created)} directories/files. Run 'cli.py sync-all' to sync.")


def readiness_run(args: argparse.Namespace) -> None:
    """Assess codebase governance readiness across 6 dimensions."""
    import json

    from core.config import get_config

    cfg = get_config()
    fw_dir = ROOT_DIR / cfg.framework_dir
    vault_dir = ROOT_DIR / ".vault"

    # Dimension 1: Documentation (.vault/ health)
    doc_score = 1
    doc_detail = "No .vault/ directory"
    if vault_dir.exists():
        # Count docs across all doc_types
        doc_types = ["adr", "plan", "research", "reference", "exec"]
        all_docs = list(vault_dir.rglob("*.md"))
        doc_count = len(all_docs)
        present_types = {
            dt
            for dt in doc_types
            if (vault_dir / dt).exists() and any((vault_dir / dt).glob("*.md"))
        }

        if doc_count < 5:
            doc_score = 2
            doc_detail = f"{doc_count} docs, needs more coverage"
        elif doc_count < 20:
            doc_score = 3
            missing = set(doc_types) - present_types
            if missing:
                doc_detail = f"{doc_count} docs, missing: {', '.join(missing)}"
            else:
                doc_detail = f"{doc_count} docs, all types present"
        elif doc_count < 50:
            doc_score = 4
            doc_detail = f"{doc_count} docs, all types present"
        else:
            doc_score = 5
            doc_detail = f"{doc_count} docs, comprehensive coverage"

    # Dimension 2: Framework (.vaultspec/ structure)
    fw_score = 1
    fw_detail = "No .vaultspec/ directory"
    if fw_dir.exists():
        has_agents = (fw_dir / "agents").exists() and any(
            (fw_dir / "agents").glob("*.md")
        )
        has_skills = (fw_dir / "skills").exists() and any(
            (fw_dir / "skills").glob("*.md")
        )
        has_rules = (fw_dir / "rules").exists() and any((fw_dir / "rules").glob("*.md"))
        has_system = (fw_dir / "system").exists()
        has_templates = (fw_dir / "templates").exists()

        if any([has_agents, has_skills, has_rules]):
            fw_score = 3
            parts = []
            if has_agents:
                parts.append("agents")
            if has_skills:
                parts.append("skills")
            if has_rules:
                parts.append("rules")
            fw_detail = f"Has {', '.join(parts)}"
        else:
            fw_score = 2
            fw_detail = ".vaultspec/ exists but minimal content"

        if has_agents and has_skills and has_rules and has_system:
            fw_score = 4
            fw_detail = "Complete structure with system/"

        if fw_score == 4 and has_templates:
            # Check for custom content (non-builtin)
            custom_count = 0
            for d in [fw_dir / "agents", fw_dir / "skills", fw_dir / "rules"]:
                if d.exists():
                    custom_count += len(
                        [
                            f
                            for f in d.glob("*.md")
                            if not f.name.endswith(".builtin.md")
                        ]
                    )
            if custom_count > 0:
                fw_score = 5
                fw_detail = f"Complete + {custom_count} custom resources"

    # Dimension 3: Rules & Governance
    rules_score = 1
    rules_detail = "No rules defined"
    if (fw_dir / "rules").exists():
        all_rules = list((fw_dir / "rules").glob("*.md"))
        builtin = [r for r in all_rules if r.name.endswith(".builtin.md")]
        custom = [r for r in all_rules if not r.name.endswith(".builtin.md")]
        total_rules = len(all_rules)

        if total_rules == 0:
            rules_score = 1
            rules_detail = "No rules defined"
        elif total_rules <= 2:
            rules_score = 2
            rules_detail = f"{total_rules} rule(s)"
        elif len(custom) == 0:
            rules_score = 3
            rules_detail = f"{total_rules} builtin rules"
        elif len(custom) > 0:
            rules_score = 4
            rules_detail = f"{len(builtin)} builtin + {len(custom)} custom"

        # Check if synced to all tool destinations
        if rules_score >= 4:
            synced_count = 0
            for cfg_item in TOOL_CONFIGS.values():
                if (
                    cfg_item.rules_dir
                    and cfg_item.rules_dir.exists()
                    and any(cfg_item.rules_dir.glob("*.md"))
                ):
                    synced_count += 1
            if synced_count >= 3:  # claude, gemini, agent
                rules_score = 5
                rules_detail += ", synced to all tools"

    # Dimension 4: Agent Coverage
    agent_score = 1
    agent_detail = "No agents"
    if (fw_dir / "agents").exists():
        agents = list((fw_dir / "agents").glob("*.md"))
        agent_count = len(agents)

        if agent_count == 0:
            agent_score = 1
            agent_detail = "No agents"
        elif agent_count <= 2:
            agent_score = 2
            agent_detail = f"{agent_count} agent(s)"
        elif agent_count <= 5:
            agent_score = 3
            agent_detail = f"{agent_count} agents covering basic roles"
        else:
            # Check tier assignments
            tier_count = 0
            for agent_file in agents:
                content = agent_file.read_text(encoding="utf-8")
                meta, _body = parse_frontmatter(content)
                if "tier" in meta:
                    tier_count += 1

            agent_score = 4
            agent_detail = f"{agent_count} agents with tier assignments"

            # Check if synced
            synced_count = 0
            for cfg_item in TOOL_CONFIGS.values():
                if (
                    cfg_item.agents_dir
                    and cfg_item.agents_dir.exists()
                    and any(cfg_item.agents_dir.glob("*.md"))
                ):
                    synced_count += 1
            if synced_count >= 2 and tier_count == agent_count:
                agent_score = 5
                agent_detail = f"{agent_count} agents, all synced"

    # Dimension 5: Test Infrastructure
    test_score = 1
    test_detail = "No test files found"
    test_dirs = [
        ROOT_DIR / ".vaultspec" / "lib" / "tests",
        ROOT_DIR / ".vaultspec" / "lib" / "src",
    ]
    test_files = []
    for test_dir in test_dirs:
        if test_dir.exists():
            test_files.extend(list(test_dir.rglob("test_*.py")))

    if test_files:
        test_score = 2
        test_detail = f"{len(test_files)} test files"

        # Check for pytest markers
        has_markers = False
        for tf in test_files[:10]:  # Sample first 10
            content = tf.read_text(encoding="utf-8")
            if "@pytest.mark." in content:
                has_markers = True
                break

        if has_markers:
            test_score = 3
            test_detail = f"{len(test_files)} tests with pytest markers"

        # Check for conftest.py (organized fixtures)
        conftest_files = []
        for test_dir in test_dirs:
            if test_dir.exists():
                conftest_files.extend(list(test_dir.rglob("conftest.py")))
        if conftest_files:
            test_score = 4
            test_detail = f"{len(test_files)} tests, {len(conftest_files)} fixtures"

        # Check for CI pipeline or benchmarks
        ci_files = [
            ROOT_DIR / ".github" / "workflows",
            ROOT_DIR / ".vaultspec" / "lib" / "tests" / "benchmarks",
        ]
        has_ci = any(d.exists() for d in ci_files)
        if has_ci:
            test_score = 5
            test_detail = f"{len(test_files)} tests + CI/benchmarks"

    # Dimension 6: Environment (GPU/deps)
    env_score = 1
    env_detail = "Missing Python or critical deps"

    try:
        # Python OK
        env_score = 2
        py_ver = f"{sys.version_info.major}.{sys.version_info.minor}"
        env_detail = f"Python {py_ver}, no GPU detected"

        # Check GPU
        try:
            import torch

            if torch.cuda.is_available():
                env_score = 3
                props = torch.cuda.get_device_properties(0)
                gpu_name = props.name
                env_detail = f"GPU: {gpu_name}"

                # Check for optional deps
                try:
                    import lancedb  # noqa: F401
                    import sentence_transformers  # noqa: F401

                    env_score = 4
                    env_detail = f"GPU + all deps, {gpu_name}"
                except ImportError:
                    env_detail = f"GPU: {gpu_name}, missing optional deps"

                # Check for .lance index
                lance_dir = ROOT_DIR / ".vault" / ".lance"
                if lance_dir.exists():
                    env_score = 5
                    env_detail = f"Full env + .lance index, {gpu_name}"
        except ImportError:
            pass  # No torch, stay at score 2
    except Exception:
        env_score = 1
        env_detail = "Environment check failed"

    # Build results
    dimensions: dict[str, dict[str, int | str]] = {
        "documentation": {"score": doc_score, "max": 5, "detail": doc_detail},
        "framework": {"score": fw_score, "max": 5, "detail": fw_detail},
        "rules_governance": {
            "score": rules_score,
            "max": 5,
            "detail": rules_detail,
        },
        "agent_coverage": {
            "score": agent_score,
            "max": 5,
            "detail": agent_detail,
        },
        "test_infrastructure": {
            "score": test_score,
            "max": 5,
            "detail": test_detail,
        },
        "environment": {"score": env_score, "max": 5, "detail": env_detail},
    }

    total_score = sum(int(d["score"]) for d in dimensions.values())
    max_total = sum(int(d["max"]) for d in dimensions.values())
    overall = total_score / max_total * 5 if max_total > 0 else 0

    # Generate recommendations
    recommendations = []
    if doc_score < 4:
        recommendations.append(
            "Add more documentation across ADRs, plans, research, references"
        )
    if fw_score < 4:
        recommendations.append("Complete .vaultspec/ structure with system/")
    if rules_score < 4:
        recommendations.append("Create custom rules for project conventions")
    if rules_score == 4:
        recommendations.append("Run 'cli.py sync-all' to sync rules to all tools")
    if agent_score < 4:
        recommendations.append("Add more agents with tier assignments")
    if agent_score == 4:
        recommendations.append("Run 'cli.py agents sync' to sync agents")
    if test_score < 5:
        recommendations.append("Add CI pipeline for automated testing")
    if env_score < 4:
        recommendations.append("Install optional dependencies (lancedb, etc.)")
    if env_score == 4:
        recommendations.append("Run 'docs.py index' to build .lance index")

    # Output
    if getattr(args, "json", False):
        result = {
            "dimensions": dimensions,
            "overall": round(overall, 1),
            "total": total_score,
            "max_total": max_total,
            "recommendations": recommendations,
        }
        print(json.dumps(result, indent=2))
    else:
        # Text output
        print("vaultspec Readiness Assessment")
        print("=" * 62)
        print()

        # Progress bar helper
        def _bar(score: int, max_score: int = 5) -> str:
            filled = "#" * score
            empty = "-" * (max_score - score)
            return filled + empty

        # Print dimensions
        labels = [
            ("Documentation", "documentation"),
            ("Framework", "framework"),
            ("Rules & Governance", "rules_governance"),
            ("Agent Coverage", "agent_coverage"),
            ("Test Infrastructure", "test_infrastructure"),
            ("Environment", "environment"),
        ]
        for label, key in labels:
            dim = dimensions[key]
            bar = _bar(int(dim["score"]), int(dim["max"]))
            score_str = f"{dim['score']}/{dim['max']}"
            detail = dim["detail"]
            print(f"{label:<22} {bar} {score_str:>3}  ({detail})")

        print()
        print(f"Overall: {overall:.1f}/5 ({total_score}/{max_total})")

        if recommendations:
            print()
            print("Recommendations:")
            for rec in recommendations:
                print(f"  - {rec}")


# ---------------------------------------------------------------
# Hooks
# ---------------------------------------------------------------


def hooks_list(_args: argparse.Namespace) -> None:
    """List all defined hooks."""
    from hooks.engine import SUPPORTED_EVENTS, load_hooks

    hooks = load_hooks(HOOKS_DIR)
    if not hooks:
        print("No hooks defined.")
        print(f"  Add .yaml files to {HOOKS_DIR.relative_to(ROOT_DIR)}/")
        print(f"\nSupported events: {', '.join(sorted(SUPPORTED_EVENTS))}")
        return

    for hook in hooks:
        status = "enabled" if hook.enabled else "disabled"
        print(f"  {hook.name} [{status}]")
        print(f"    event: {hook.event}")
        for action in hook.actions:
            if action.action_type == "shell":
                print(f"    -> shell: {action.command}")
            elif action.action_type == "agent":
                print(f"    -> agent: {action.agent_name}")


def hooks_run(args: argparse.Namespace) -> None:
    """Manually trigger hooks for a given event."""
    from hooks.engine import SUPPORTED_EVENTS, load_hooks, trigger

    event = args.event
    if event not in SUPPORTED_EVENTS:
        print(f"Unknown event: {event}")
        print(f"Supported: {', '.join(sorted(SUPPORTED_EVENTS))}")
        return

    hooks = load_hooks(HOOKS_DIR)
    matching = [h for h in hooks if h.event == event and h.enabled]
    if not matching:
        print(f"No enabled hooks for event: {event}")
        return

    ctx = {"root": str(ROOT_DIR), "event": event}
    if hasattr(args, "path") and args.path:
        ctx["path"] = args.path

    print(f"Triggering {len(matching)} hook(s) for '{event}'...")
    results = trigger(hooks, event, ctx)
    for r in results:
        icon = "[OK]" if r.success else "[FAIL]"
        print(f"  {r.hook_name} ({r.action_type}): {icon}")
        if r.output:
            for line in r.output.splitlines()[:5]:
                print(f"    {line}")
        if r.error:
            print(f"    error: {r.error}")


def add_sync_flags(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--prune", action="store_true", help="Remove unknown files")
    parser.add_argument("--dry-run", action="store_true", help="Preview changes")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Manage rules, agents, and skills across tool destinations.",
        prog="cli.py",
    )
    parser.add_argument(
        "--root", type=Path, default=None, help="Override workspace root"
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Enable verbose output (INFO level)",
    )
    parser.add_argument(
        "--debug", action="store_true", help="Enable debug logging (DEBUG level)"
    )
    parser.add_argument(
        "--version", "-V", action="version", version=f"%(prog)s {_get_version()}"
    )
    resource_parsers = parser.add_subparsers(dest="resource", help="Type")

    # --- rules ---
    rules_parser = resource_parsers.add_parser("rules", help="Manage rules")
    rules_sub = rules_parser.add_subparsers(dest="command")

    rules_sub.add_parser("list", help="List all rules")

    rules_add_parser = rules_sub.add_parser("add", help="Add a custom rule")
    rules_add_parser.add_argument("--name", required=True, help="Rule name")
    rules_add_parser.add_argument("--content", help="Rule content")
    rules_add_parser.add_argument("--force", action="store_true", help="Overwrite")

    rules_show_parser = rules_sub.add_parser("show", help="Show a rule")
    rules_show_parser.add_argument("name", help="Rule name")

    rules_edit_parser = rules_sub.add_parser("edit", help="Edit a rule")
    rules_edit_parser.add_argument("name", help="Rule name")

    rules_remove_parser = rules_sub.add_parser("remove", help="Remove a rule")
    rules_remove_parser.add_argument("name", help="Rule name")
    rules_remove_parser.add_argument(
        "--force", action="store_true", help="Skip confirmation"
    )

    rules_rename_parser = rules_sub.add_parser("rename", help="Rename a rule")
    rules_rename_parser.add_argument("old_name", help="Current name")
    rules_rename_parser.add_argument("new_name", help="New name")

    rules_sync_parser = rules_sub.add_parser("sync", help="Sync rules")
    add_sync_flags(rules_sync_parser)

    # --- agents ---
    agents_parser = resource_parsers.add_parser("agents", help="Manage agents")
    agents_sub = agents_parser.add_subparsers(dest="command")

    agents_sub.add_parser("list", help="List all agents")

    agents_add_parser = agents_sub.add_parser("add", help="Add a new agent")
    agents_add_parser.add_argument("--name", required=True, help="Agent name")
    agents_add_parser.add_argument(
        "--description", default="", help="Agent description"
    )
    agents_add_parser.add_argument(
        "--tier",
        default="MEDIUM",
        choices=["LOW", "MEDIUM", "HIGH"],
        help="Capability tier",
    )
    agents_add_parser.add_argument("--force", action="store_true", help="Overwrite")
    agents_add_parser.add_argument(
        "--template", help="Template name from .vaultspec/templates/ to pre-populate"
    )

    agents_show_parser = agents_sub.add_parser("show", help="Show an agent")
    agents_show_parser.add_argument("name", help="Agent name")

    agents_edit_parser = agents_sub.add_parser("edit", help="Edit an agent")
    agents_edit_parser.add_argument("name", help="Agent name")

    agents_remove_parser = agents_sub.add_parser("remove", help="Remove an agent")
    agents_remove_parser.add_argument("name", help="Agent name")
    agents_remove_parser.add_argument(
        "--force", action="store_true", help="Skip confirmation"
    )

    agents_rename_parser = agents_sub.add_parser("rename", help="Rename an agent")
    agents_rename_parser.add_argument("old_name", help="Current name")
    agents_rename_parser.add_argument("new_name", help="New name")

    agents_sync_parser = agents_sub.add_parser("sync", help="Sync agents")
    add_sync_flags(agents_sync_parser)

    agents_tier_parser = agents_sub.add_parser("set-tier", help="Update agent tier")
    agents_tier_parser.add_argument("name", help="Agent name")
    agents_tier_parser.add_argument(
        "--tier", required=True, choices=["LOW", "MEDIUM", "HIGH"], help="Tier"
    )

    # --- skills ---
    skills_parser = resource_parsers.add_parser("skills", help="Manage skills")
    skills_sub = skills_parser.add_subparsers(dest="command")

    skills_sub.add_parser("list", help="List all managed skills")

    skills_add_parser = skills_sub.add_parser("add", help="Add a new skill")
    skills_add_parser.add_argument("--name", required=True, help="Skill name")
    skills_add_parser.add_argument(
        "--description", default="", help="Skill description"
    )
    skills_add_parser.add_argument("--force", action="store_true", help="Overwrite")
    skills_add_parser.add_argument(
        "--template", help="Template name from .vaultspec/templates/ to pre-populate"
    )

    skills_show_parser = skills_sub.add_parser("show", help="Show a skill")
    skills_show_parser.add_argument("name", help="Skill name")

    skills_edit_parser = skills_sub.add_parser("edit", help="Edit a skill")
    skills_edit_parser.add_argument("name", help="Skill name")

    skills_remove_parser = skills_sub.add_parser("remove", help="Remove a skill")
    skills_remove_parser.add_argument("name", help="Skill name")
    skills_remove_parser.add_argument(
        "--force", action="store_true", help="Skip confirmation"
    )

    skills_rename_parser = skills_sub.add_parser("rename", help="Rename a skill")
    skills_rename_parser.add_argument("old_name", help="Current name")
    skills_rename_parser.add_argument("new_name", help="New name")

    skills_sync_parser = skills_sub.add_parser("sync", help="Sync skills")
    add_sync_flags(skills_sync_parser)

    # --- constitution ---
    constitution_parser = resource_parsers.add_parser(
        "constitution", help="Manage constitution"
    )
    constitution_sub = constitution_parser.add_subparsers(dest="command")

    constitution_sub.add_parser("show", help="Display constitution")

    constitution_init_parser = constitution_sub.add_parser(
        "init", help="Create constitution from template"
    )
    constitution_init_parser.add_argument(
        "--force", action="store_true", help="Overwrite existing"
    )

    # --- config ---
    config_parser = resource_parsers.add_parser(
        "config", help="Manage tool configs (CLAUDE.md, GEMINI.md)"
    )
    config_sub = config_parser.add_subparsers(dest="command")

    config_sub.add_parser("show", help="Display internal/custom content")

    config_sync_parser = config_sub.add_parser("sync", help="Sync configs")
    add_sync_flags(config_sync_parser)
    config_sync_parser.add_argument(
        "--force", action="store_true", help="Overwrite custom content"
    )

    # --- system ---
    system_parser = resource_parsers.add_parser("system", help="Manage system prompts")
    system_sub = system_parser.add_subparsers(dest="command")

    system_sub.add_parser("show", help="Display system parts and targets")

    system_sync_parser = system_sub.add_parser("sync", help="Sync system prompts")
    add_sync_flags(system_sync_parser)
    system_sync_parser.add_argument(
        "--force", action="store_true", help="Overwrite custom content"
    )

    # --- sync-all ---
    sync_all_parser = resource_parsers.add_parser("sync-all", help="Sync all")
    add_sync_flags(sync_all_parser)
    sync_all_parser.add_argument("--force", action="store_true", help="Force overwrite")

    # --- test ---
    test_parser = resource_parsers.add_parser("test", help="Run tests")
    test_parser.add_argument(
        "category",
        nargs="?",
        default="all",
        choices=["all", "unit", "api", "search", "index", "quality"],
        help="Test category (default: all)",
    )
    test_parser.add_argument(
        "--module",
        "-m",
        choices=["cli", "rag", "vault", "protocol", "orchestration", "subagent"],
        help="Filter by module",
    )
    test_parser.add_argument("extra_args", nargs="*", help="Extra pytest arguments")

    # --- doctor ---
    resource_parsers.add_parser("doctor", help="Check prerequisites and system health")

    # --- init ---
    init_parser = resource_parsers.add_parser(
        "init", help="Initialize vaultspec in a project"
    )
    init_parser.add_argument(
        "--force", action="store_true", help="Overwrite existing structure"
    )

    # --- readiness ---
    readiness_parser = resource_parsers.add_parser(
        "readiness", help="Assess codebase governance readiness"
    )
    readiness_parser.add_argument("--json", action="store_true", help="Output as JSON")

    # --- hooks ---
    hooks_parser = resource_parsers.add_parser(
        "hooks", help="Manage event-driven hooks"
    )
    hooks_sub = hooks_parser.add_subparsers(dest="command")
    hooks_sub.add_parser("list", help="List all hooks")
    hooks_run_parser = hooks_sub.add_parser("run", help="Trigger hooks for an event")
    hooks_run_parser.add_argument("event", help="Event name")
    hooks_run_parser.add_argument("--path", help="Context path variable")

    args = parser.parse_args()

    if args.debug:
        configure_logging(level="DEBUG")
    elif args.verbose:
        configure_logging(level="INFO")
    else:
        configure_logging()

    if args.root is not None:
        init_paths(args.root.resolve())

    if args.resource == "rules":
        if args.command == "list":
            rules_list(args)
        elif args.command == "add":
            rules_add(args)
        elif args.command == "show":
            resource_show(args, RULES_SRC_DIR, "Rule")
        elif args.command == "edit":
            resource_edit(args, RULES_SRC_DIR, "Rule")
        elif args.command == "remove":
            resource_remove(args, RULES_SRC_DIR, "Rule")
        elif args.command == "rename":
            resource_rename(args, RULES_SRC_DIR, "Rule")
        elif args.command == "sync":
            rules_sync(args)
        else:
            rules_parser.print_help()
    elif args.resource == "agents":
        if args.command == "list":
            agents_list(args)
        elif args.command == "add":
            agents_add(args)
        elif args.command == "show":
            resource_show(args, AGENTS_SRC_DIR, "Agent")
        elif args.command == "edit":
            resource_edit(args, AGENTS_SRC_DIR, "Agent")
        elif args.command == "remove":
            resource_remove(args, AGENTS_SRC_DIR, "Agent")
        elif args.command == "rename":
            resource_rename(args, AGENTS_SRC_DIR, "Agent")
        elif args.command == "sync":
            agents_sync(args)
        elif args.command == "set-tier":
            agents_set_tier(args)
        else:
            agents_parser.print_help()
    elif args.resource == "skills":
        if args.command == "list":
            skills_list(args)
        elif args.command == "add":
            skills_add(args)
        elif args.command == "show":
            resource_show(args, SKILLS_SRC_DIR, "Skill")
        elif args.command == "edit":
            resource_edit(args, SKILLS_SRC_DIR, "Skill")
        elif args.command == "remove":
            resource_remove(args, SKILLS_SRC_DIR, "Skill")
        elif args.command == "rename":
            resource_rename(args, SKILLS_SRC_DIR, "Skill")
        elif args.command == "sync":
            skills_sync(args)
        else:
            skills_parser.print_help()
    elif args.resource == "constitution":
        if args.command == "show":
            constitution_show(args)
        elif args.command == "init":
            constitution_init(args)
        else:
            constitution_parser.print_help()
    elif args.resource == "config":
        if args.command == "show":
            config_show(args)
        elif args.command == "sync":
            config_sync(args)
        else:
            config_parser.print_help()
    elif args.resource == "system":
        if args.command == "show":
            system_show(args)
        elif args.command == "sync":
            system_sync(args)
        else:
            system_parser.print_help()
    elif args.resource == "test":
        test_run(args)
    elif args.resource == "sync-all":
        print("Syncing all resources...")
        rules_sync(args)
        agents_sync(args)
        skills_sync(args)
        system_sync(args)
        config_sync(args)
        print("Done.")
    elif args.resource == "doctor":
        doctor_run(args)
    elif args.resource == "init":
        init_run(args)
    elif args.resource == "readiness":
        readiness_run(args)
    elif args.resource == "hooks":
        if args.command == "list":
            hooks_list(args)
        elif args.command == "run":
            hooks_run(args)
        else:
            hooks_parser.print_help()
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
