"""Parse/file-operation tests for the CLI sync engine.

Covers: frontmatter parsing, build_file, atomic_write, _is_cli_managed,
init_paths, SyncResult.
"""

from __future__ import annotations

import pytest

from ...core import init_paths
from ...core.config_gen import _is_cli_managed
from ...core.enums import Tool
from ...core.helpers import atomic_write, build_file
from ...core.sync import format_summary
from ...core.types import SyncResult
from ...vaultcore import parse_frontmatter

pytestmark = [pytest.mark.unit]


def _cfg(tool: Tool):
    from ...core import types as _t

    return _t.get_context().tool_configs[tool]


class TestFrontmatter:
    def test_parse_simple(self, test_project):
        content = "---\nname: test\n---\nbody"
        meta, body = parse_frontmatter(content)
        assert meta == {"name": "test"}
        assert body == "body"

    def test_parse_no_frontmatter(self, test_project):
        content = "just body"
        meta, body = parse_frontmatter(content)
        assert meta == {}
        assert body == "just body"

    def test_parse_empty(self, test_project):
        meta, body = parse_frontmatter("")
        assert meta == {}
        assert body == ""


class TestIsCliManaged:
    def test_managed_content(self, test_project):
        content = "<!-- AUTO-GENERATED by cli.py config sync. -->\nSome config"
        assert _is_cli_managed(content) is True

    def test_custom_content(self, test_project):
        assert _is_cli_managed("# My custom config") is False

    def test_path_managed(self, tmp_path, test_project):
        p = tmp_path / "managed.md"
        p.write_text("<!-- AUTO-GENERATED by cli.py config sync. -->", encoding="utf-8")
        assert _is_cli_managed(p) is True

    def test_path_custom(self, tmp_path, test_project):
        p = tmp_path / "custom.md"
        p.write_text("plain text", encoding="utf-8")
        assert _is_cli_managed(p) is False

    def test_path_nonexistent(self, tmp_path, test_project):
        assert _is_cli_managed(tmp_path / "missing.md") is False


class TestBuildFile:
    def test_assembles_correctly(self, test_project):
        fm = {"name": "test-rule", "trigger": "always_on"}
        body = "# My Rule\n\nDo the thing."
        output = build_file(fm, body)
        assert output.startswith("---\n")
        assert "---\n\n" in output
        assert "name: test-rule" in output
        assert "trigger: always_on" in output
        assert "# My Rule" in output

    def test_empty_body(self, test_project):
        fm = {"name": "empty"}
        output = build_file(fm, "")
        assert output.endswith("---\n\n")
        meta2, body2 = parse_frontmatter(output)
        assert meta2 == fm
        assert body2 == ""


class TestAtomicWrite:
    def test_creates_new_file(self, test_project):
        p = test_project / "new.md"
        atomic_write(p, "hello world")
        assert p.read_text(encoding="utf-8") == "hello world"

    def test_overwrites_existing(self, test_project):
        p = test_project / "existing.md"
        p.write_text("old content", encoding="utf-8")
        atomic_write(p, "new content")
        assert p.read_text(encoding="utf-8") == "new content"

    def test_no_temp_file_left(self, test_project):
        p = test_project / "clean.md"
        atomic_write(p, "data")
        assert not (test_project / "clean.md.tmp").exists()


class TestInitPaths:
    def test_sets_context(self, test_project):
        from ...core import types as _t

        init_paths(test_project)
        ctx = _t.get_context()
        assert test_project == ctx.root_dir
        assert ctx.rules_src_dir.name == "rules"
        assert ctx.skills_src_dir.name == "skills"

    def test_tool_configs_populated(self, test_project):
        from ...core import types as _t

        init_paths(test_project)
        ctx = _t.get_context()
        assert Tool.CLAUDE in ctx.tool_configs
        assert Tool.GEMINI in ctx.tool_configs
        assert Tool.ANTIGRAVITY in ctx.tool_configs
        assert Tool.CODEX in ctx.tool_configs
        assert _cfg(Tool.CLAUDE).name == "claude"
        assert _cfg(Tool.ANTIGRAVITY).config_file == test_project / "GEMINI.md"
        assert _cfg(Tool.ANTIGRAVITY).rules_dir == (test_project / ".agents" / "rules")
        assert _cfg(Tool.ANTIGRAVITY).skills_dir == (
            test_project / ".agents" / "skills"
        )
        assert _cfg(Tool.CODEX).config_file == test_project / "AGENTS.md"
        assert _cfg(Tool.CODEX).native_config_file == (
            test_project / ".codex" / "config.toml"
        )
        assert _cfg(Tool.CODEX).rules_dir is None
        assert _cfg(Tool.CODEX).skills_dir == (test_project / ".agents" / "skills")
        assert _cfg(Tool.CODEX).rule_ref_dir is None
        # Claude config at project root
        assert _cfg(Tool.CLAUDE).config_file == test_project / "CLAUDE.md"
        # Gemini config at project root, skills via .agents/
        assert _cfg(Tool.GEMINI).config_file == test_project / "GEMINI.md"
        assert _cfg(Tool.GEMINI).skills_dir == (test_project / ".agents" / "skills")


class TestSyncResult:
    def test_default_values(self, test_project):
        r = SyncResult()
        assert r.added == 0
        assert r.updated == 0
        assert r.pruned == 0
        assert r.skipped == 0
        assert r.errors == []


class TestFormatSummary:
    def test_format_summary_no_changes(self, test_project):
        result = format_summary("Test", SyncResult())
        assert "no changes" in result

    def test_format_summary_with_counts(self, test_project):
        r = SyncResult(added=2, updated=1, pruned=3)
        result = format_summary("Rules", r)
        assert "2 added" in result
        assert "1 updated" in result
        assert "3 pruned" in result
