"""Parse/file-operation tests for the CLI sync engine.

Covers: frontmatter parsing, build_file, atomic_write, _is_cli_managed,
init_paths, SyncResult.
"""

from __future__ import annotations

import pytest

from ...core import init_paths
from ...core.config_gen import _is_cli_managed
from ...core.helpers import atomic_write, build_file
from ...core.sync import print_summary
from ...core.types import SyncResult
from ...vaultcore import parse_frontmatter

pytestmark = [pytest.mark.unit]


class TestFrontmatter:
    def test_parse_simple(self, test_project):
        content = "---\nname: test\n---\nbody"
        meta, body = parse_frontmatter(content)
        assert meta == {"name": "test"}
        assert body == "body"

    def test_parse_no_frontmatter(self, test_project):
        content = "just body"
        meta, body = parse_frontmatter(content)
        assert meta == {}
        assert body == "just body"

    def test_parse_empty(self, test_project):
        meta, body = parse_frontmatter("")
        assert meta == {}
        assert body == ""


class TestIsCliManaged:
    def test_managed_content(self, test_project):
        content = "<!-- AUTO-GENERATED by cli.py config sync. -->\nSome config"
        assert _is_cli_managed(content) is True

    def test_custom_content(self, test_project):
        assert _is_cli_managed("# My custom config") is False

    def test_path_managed(self, tmp_path, test_project):
        p = tmp_path / "managed.md"
        p.write_text("<!-- AUTO-GENERATED by cli.py config sync. -->", encoding="utf-8")
        assert _is_cli_managed(p) is True

    def test_path_custom(self, tmp_path, test_project):
        p = tmp_path / "custom.md"
        p.write_text("plain text", encoding="utf-8")
        assert _is_cli_managed(p) is False

    def test_path_nonexistent(self, tmp_path, test_project):
        assert _is_cli_managed(tmp_path / "missing.md") is False


class TestBuildFile:
    def test_assembles_correctly(self, test_project):
        fm = {"name": "test-rule", "trigger": "always_on"}
        body = "# My Rule\n\nDo the thing."
        output = build_file(fm, body)
        assert output.startswith("---\n")
        assert "---\n\n" in output
        assert "name: test-rule" in output
        assert "trigger: always_on" in output
        assert "# My Rule" in output

    def test_empty_body(self, test_project):
        fm = {"name": "empty"}
        output = build_file(fm, "")
        assert output.endswith("---\n\n")
        meta2, body2 = parse_frontmatter(output)
        assert meta2 == fm
        assert body2 == ""


class TestAtomicWrite:
    def test_creates_new_file(self, test_project):
        p = test_project / "new.md"
        atomic_write(p, "hello world")
        assert p.read_text(encoding="utf-8") == "hello world"

    def test_overwrites_existing(self, test_project):
        p = test_project / "existing.md"
        p.write_text("old content", encoding="utf-8")
        atomic_write(p, "new content")
        assert p.read_text(encoding="utf-8") == "new content"

    def test_no_temp_file_left(self, test_project):
        p = test_project / "clean.md"
        atomic_write(p, "data")
        assert not (test_project / "clean.md.tmp").exists()


class TestInitPaths:
    def test_sets_globals(self, test_project):
        from ...core import types as _t

        init_paths(test_project)
        assert test_project == _t.ROOT_DIR
        assert _t.RULES_SRC_DIR.name == "rules"
        assert _t.SKILLS_SRC_DIR.name == "skills"

    def test_tool_configs_populated(self, test_project):
        from ...core import types as _t

        init_paths(test_project)
        assert "claude" in _t.TOOL_CONFIGS
        assert "gemini" in _t.TOOL_CONFIGS
        assert "antigravity" in _t.TOOL_CONFIGS
        assert "codex" in _t.TOOL_CONFIGS
        assert _t.TOOL_CONFIGS["claude"].name == "claude"
        assert _t.TOOL_CONFIGS["antigravity"].config_file == test_project / "GEMINI.md"
        assert _t.TOOL_CONFIGS["antigravity"].rules_dir == (
            test_project / ".agents" / "rules"
        )
        assert _t.TOOL_CONFIGS["antigravity"].skills_dir == (
            test_project / ".agents" / "skills"
        )
        assert _t.TOOL_CONFIGS["codex"].config_file is None
        assert _t.TOOL_CONFIGS["codex"].native_config_file == (
            test_project / ".codex" / "config.toml"
        )
        assert _t.TOOL_CONFIGS["codex"].rules_dir is None
        assert _t.TOOL_CONFIGS["codex"].skills_dir == (
            test_project / ".agents" / "skills"
        )
        assert _t.TOOL_CONFIGS["codex"].rule_ref_dir is None


class TestSyncResult:
    def test_default_values(self, test_project):
        r = SyncResult()
        assert r.added == 0
        assert r.updated == 0
        assert r.pruned == 0
        assert r.skipped == 0
        assert r.errors == []


class TestPrintSummary:
    def test_print_summary_no_changes(self, capsys, test_project):
        print_summary("Test", SyncResult())
        captured = capsys.readouterr()
        assert "no changes" in captured.out

    def test_print_summary_with_counts(self, capsys, test_project):
        r = SyncResult(added=2, updated=1, pruned=3)
        print_summary("Rules", r)
        captured = capsys.readouterr()
        assert "2 added" in captured.out
        assert "1 updated" in captured.out
        assert "3 pruned" in captured.out
